### ISSUE TITLE
Define scope of this project

### ISSUE THREAD

**Issue by vladdu** [erlang-ls/erlang_ls#1]
What do we want from this project? 
- A common LS implementation? 
- An extended LSP with Erlang-specific methods? Would those pertain to editing code, or do we include debugging and other interactions with live runtimes?
- Do we want to include other BEAM languages?

**Comment by robertoaloi** [comment]
The idea behind the GitHub organization is to have a common space for members of the Erlang community who want to leverage the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol) to improve support for the [Erlang](http://www.erlang.org/) programming language in the most common editors and IDEs (e.g. Emacs, Vim, Eclipse, VS, etc).

The goal of this specific repo/project is to define and implement a single, common, language server implementation (in Erlang) that is decoupled from the editor-specifics. The implementation could leverage existing implementations (if the respective authors decide to become collaborators) or a new one from scratch. The common implementation should be a full implementation of the protocol, fully reviewed, documented and tested.

I haven't been looking at protocol extensions or Erlang-specific methods yet, but they sound like something that should probably be implemented as a separate library under the same organization. Everything is still open for discussion.

Eventual clients and extensions of the common server are welcome as separate repositories under the same organization.

For the time being, the project focuses on Erlang only, but things can change depending on interest.

I will add something like this to the description/README. Feedback welcome.

**Comment by robertoaloi** [comment]
Added a "rationale" section to the README. For now, I would keep the scope very limited. This means essentially:

* Just the Language Server, no extensions (e.g. a BuildLS or a DebugLS)
* No other BEAM languages for the time being

I would leave the above items only to a second phase, when the basis is ready.
