### ISSUE TITLE
Unused macro is actually used

### ISSUE THREAD

**Issue by rlipscombe** [erlang-ls/erlang_ls#1021]
**Describe the bug**
ErlangLS warns about an unused macro. But the macro _is_ actually being used.

**To Reproduce**
```erlang
-module(foo).
-export([bar/0]).

-define(BAZ, baz).  % Unused macro: BAZ (incorrect)
-define(QUUX, quux).
-define(FNORD, fnord).  % Unused macro: FNORD (correct)

bar() ->
    % ...but it _is_ used.
    ?BAZ:call(?QUUX).
```

**Expected behavior**
- BAZ should not be reported as unused, because it is used. This is the bug.
- QUUX should not be reported as unused, because it is used. This is a control.
- FNORD should be reported as unused, because it is not used. This is a control.

**Actual behavior**
See comments in the snippet above.

**Context**
 - `erlang_ls` version (tag/sha): 0.15.0
 - Editor used: VS Code 1.56.2
 - LSP client used: erlang-ls.erlang-ls extension, 0.0.25

**Comment by robertoaloi** [comment]
Hi @rlipscombe and thanks for the report. We'll look into it!
