### ISSUE TITLE
Behavior errors are duplicated in the using module

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#1024]
**Describe the bug**
When using the behavior directive in Erlang, Erlang LS reports compilation errors in the module where the behavior is used _in addition_ to the behavior module itself. 

**To Reproduce**
Create a behavior module that has one or more `-callback` attributes and some compilation error or warning. Use it in another module.

**Expected behavior**
Errors in the behavior module are reported in only that module. The only thing that should be reported in the using modules should be errors related to the callback implementations (type mismatches).

**Actual behavior**
Errors are duplicated in all modules.

```
src/my_behaviour.erl:
    6:1   error   function init/2 undefined ​Compiler
   23:1   error   syntax error before: 'catch' ​Compiler
   43:1   warning function format_stacktrace/1 is unused ​Compiler
   46:1   warning function format_stacktrace_entry/1 is unused ​Compiler

src/using1.erl:
    3:1   error   Issue in included file (23): syntax error before: 'catch' ​Compiler
    3:1   error   Issue in included file (6): function init/2 undefined ​Compiler
    3:1   warning Issue in included file (43): function format_stacktrace/1 is unused ​Compiler
    3:1   warning Issue in included file (46): function format_stacktrace_entry/1 is unused ​Compiler

src/using2.erl:
    3:1   error   Issue in included file (23): syntax error before: 'catch' ​Compiler
    3:1   error   Issue in included file (6): function init/2 undefined ​Compiler
    3:1   warning Issue in included file (43): function format_stacktrace/1 is unused ​Compiler
    3:1   warning Issue in included file (46): function format_stacktrace_entry/1 is unused ​Compiler

src/using3.erl:
    3:1   error   Issue in included file (23): syntax error before: 'catch' ​Compiler
    3:1   error   Issue in included file (6): function init/2 undefined ​Compiler
    3:1   warning Issue in included file (43): function format_stacktrace/1 is unused ​Compiler
    3:1   warning Issue in included file (46): function format_stacktrace_entry/1 is unused ​Compiler
```

**Context**
 - `erlang_ls` version (tag/sha): Version: 0.16.0+build.1587.ref4fc00d3
 - Editor used: Sublime Text 4 (4106)
 - LSP client used: Sublime LSP v1.4.0

Config:
```yaml
deps_dirs:
  - "_build/default/lib/*"
  - "_build/default/checkouts/*"
include_dirs:
  - "_build/default/lib/*/include"
  - "_checkouts/*/include"
```

**Comment by eproxus** [comment]
In my opinion, the reports in the using files is completely redundant and doesn't provide any value.

**Comment by robertoaloi** [comment]
Hi! If I remember the discussion when we introduced this behaviour, it was due to the cases where a module would fail recompilation or reload due to an issue in a used behaviour, creating confusion in the user. Having the diagnostics for the included file was giving a clear pointer of what the issue was.

**Comment by eproxus** [comment]
But a module can't fail recompilation because of a used behavior, can it? You can only receive warnings for not implementing callbacks?

I think these "errors" has several problems. First of all, it is not an "included file." Second, I don't need to see the error in the included file multiple times.

**Comment by robertoaloi** [comment]
What I meant is that, if the behaviour could not compile, you would get a "behaviour not defined" message. But I can also understand your point. One thing to consider is that the behaviour may not be necessarily open in the project, in which case you shouldn't see the duplicated messages. That should only happen if you have both the behaviour *and* the respective implementations open. Said that, I'm happy to revisit this and, even if we decide to keep the current behaviour, we should rephrase the error (the _included file_ is a leftover from when this was limited to `.hrl` files).

@alanz you submitted the original [issue](https://github.com/erlang-ls/erlang_ls/issues/614) and the respective [fix](https://github.com/erlang-ls/erlang_ls/pull/635). Do you have any opinions on this?

**Comment by eproxus** [comment]
It feels very confusing and not that useful that some errors would appear in some files based on what other files where open at the time?

**Comment by alanz** [comment]
The original problem being addressed was in a module using a parse transform, where the parse transform failed to compile, and no diagnostics were reported anywhere, so it was impossible to determine what he behaviour was.

So perhaps limiting this behaviour to that case might be a good approach.

**Comment by robertoaloi** [comment]
I plan to do the following:

* Only include a single warning in the line pointing to a failing dependency (behaviour, parse_transform or included file)
* Adjust the message to clarify the nature of the dependency
