### ISSUE TITLE
Have `deps_dirs` follow sym links

### ISSUE THREAD

**Issue by ankhers** [erlang-ls/erlang_ls#1046]
**Is your feature request related to a problem? Please describe.**
I have a rebar3 application that is currently being developed locally. Because none of my applications are currently on hex.pm, or anywhere else, I am using rebar3s [`checkout dependencies`](http://rebar3.org/docs/configuration/dependencies/#checkout-dependencies) at the moment. Unfortunately if I use `- "_checkouts/*"` in my `deps_dirs` configuration, the sym links do not appear to be follow as I am not getting any autocomplete for those applications.

**Describe the solution you'd like**
I would like symlinks to be followed so that I can make use of those applications

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robertoaloi** [comment]
Thanks for reporting @ankhers . I think this behaviour was introduced by https://github.com/erlang-ls/erlang_ls/pull/346. We need to find a way to handle both situations.
