### ISSUE TITLE
Invalid unused include warning when including eunit.hrl

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#1047]
**Describe the bug**
Consider the following module:
```erlang
-module(my_tests).
-include_lib("eunit/include/eunit.hrl").
the_test() -> ok.
```

A warning will be generated on line 2: `warning Unused file: eunit.hrl ​UnusedIncludes`

**To Reproduce**
Create the module.

**Expected behavior**
No warning is issued since the include file is used, because it exports the `the_test/0` function. If the file is not included, the test doesn't work.

**Actual behavior**
A false warning is issued: `warning Unused file: eunit.hrl ​UnusedIncludes`

**Context**
 - `erlang_ls` version (tag/sha): 0.17.0
 - Editor used: Sublime Text 4 (4109)
 - LSP client used: Sublime LSP v1.6.1

**Comment by gomoripeti** [comment]
thanks Adam, this is indeed a bug. Just cross-linking with the related https://github.com/erlang-ls/erlang_ls/issues/964

**Comment by robertoaloi** [comment]
What we could have (unless we manage to fix all corner cases) is a ignore-list for header files. Candidates could be:

```
eunit/include/eunit.hrl
proper/include/proper.hrl
eqc/include/eqc.hrl
pmod_transform/include/pmod.hrl
stdlib/include/qlc.hrl
stdlib/include/ms_transform.hrl
```

The user could customize the list if required. Similar to the [Exclude OTP Apps list](https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_core/src/els_config.erl#L94)

**Comment by michalmuskala** [comment]
Shouldn't any header file that includes `-parse_transform` attribute be excluded like this? I think this should cover all of the above

**Comment by robertoaloi** [comment]
That should work. I was thinking to cases "other" than parse transforms, but maybe there isn't any.

**Comment by gomoripeti** [comment]
to be very precise it is not a -parse_transform attribute, but a compiler option in a -compile attribute, but probably the presence of any compiler option should make the header be excluded.
for "other" cases Daniel brings up in the other ticket wild attributes that are not known by the compiler.

**Comment by robertoaloi** [comment]
@eproxus This should now be solved in the lastest `HEAD`, let me know how it goes.
