### ISSUE TITLE
Infinite loop when LSP log level is set to debug

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#1050]
Now that log messages are sent through the LSP tracing facilities, we have an issue.

If the log level includes DEBUG, that causes all LSP calls to be logged, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message, which in turns causes a new log message, which in turns causes a new LSP message...

**Comment by TheGeorge** [comment]
Yes, I noticed this when implementing it and honestly forget to address it. I think the log lines that cause this can be removed. The client should be able to log the messages that are send to the server without the server needing to leg these as well.
