### ISSUE TITLE
debug support requirement

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [erlang-ls/erlang_ls#1057]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
wish to support debug for vscode, useful for development

**Describe alternatives you've considered**
run erl, run im(). boring..............
i have tried another vscode plugin, it as code autocompletion and debug, but the code autocompletion is too slow; this plugin has no debug support, so if this plugin can provide debug support, it will be very good.

**Additional context**
basic no additional contexts for this feature.

Thanks.

**Comment by TheGeorge** [comment]
Are you asking if this has debugger support?

We support step debugging. Simply create a launch config, the vscode plugin
should provide sensible defaults for rebar3 based projects.

**Comment by ziyouchutuwenwu** [comment]
thanks, i found it, it works fine, thanks for your great work!

**Comment by robertoaloi** [comment]
@ziyouchutuwenwu There's now a tutorial on how to use the Erlang LS debugging functionalities: https://erlang-ls.github.io/articles/tutorial-debugger/ Hope it helps.
