### ISSUE TITLE
Code completion for Erlang keywords

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#107]
A handy list of reserved keywords is available at:

https://github.com/erlang/otp/blob/7cc8adca707e413c0449275f225567b097714318/lib/stdlib/src/erl_scan.erl#L1173

```
reserved_word('after') -> true;
reserved_word('begin') -> true;
reserved_word('case') -> true;
reserved_word('try') -> true;
reserved_word('cond') -> true;
reserved_word('catch') -> true;
reserved_word('andalso') -> true;
reserved_word('orelse') -> true;
reserved_word('end') -> true;
reserved_word('fun') -> true;
reserved_word('if') -> true;
reserved_word('let') -> true;
reserved_word('of') -> true;
reserved_word('receive') -> true;
reserved_word('when') -> true;
reserved_word('bnot') -> true;
reserved_word('not') -> true;
reserved_word('div') -> true;
reserved_word('rem') -> true;
reserved_word('band') -> true;
reserved_word('and') -> true;
reserved_word('bor') -> true;
reserved_word('bxor') -> true;
reserved_word('bsl') -> true;
reserved_word('bsr') -> true;
reserved_word('or') -> true;
reserved_word('xor') -> true;
reserved_word(_) -> false.
```

**Comment by jfacorro** [comment]
How would the server know the user is trying to enter one of these keyword?

**Comment by robertoaloi** [comment]
Let's use Emacs as an example. The idea is to trigger this kind of completions via the `completion-at-point` (`M-tab` or `M-C-i`) command. As of today, this shortcut is overwritten by the major `erlang-mode`to point to the `erlang-complete-tag`. This solution requires a TAGS file being created via the `tags` module in the `tools` application, which basically scans the Erlang files and produces a list of tags for the existing functions, macros and similar, very much like we generate the list of POIs for a specific module, but in a very fragile way. By overriding this binding to use `completion-at-point` or even better `company-lsp` you can trigger completions at your pleasure:

```
(eval-after-load 'erlang
  '(define-key erlang-mode-map (kbd "C-M-i") #'company-lsp))
```

For example, I can start typing `re`, hit `M-tab` and get the atom `receive` which is marked as a keyword.

**Comment by robertoaloi** [comment]
<img width="397" alt="Screenshot 2019-11-02 at 11 19 10" src="https://user-images.githubusercontent.com/91769/68069611-a6e29400-fd62-11e9-8b28-c8d8a16803c7.png">

**Comment by jfacorro** [comment]
But in the context of LSP server, you will also get all modules and local functions that fuzzy match with `re`, right?

I have never used the `M-tab` keybinding, `lsp-mode` provides `C-space` for sending a completion request to the server.
