### ISSUE TITLE
erlang_ls can't find definition of ?config macro from ct.hrl

### ISSUE THREAD

**Issue by NAR** [erlang-ls/erlang_ls#1073]
**Describe the bug**

The `?config` macro is used in many `common_test` testcases to fetch input data for testcases. However, `erlang_ls` doesn't seem to be able to find it's definition (and thus reports the `ct.hrl` include file unused). The problem seems to be that when `erlang_ls` parses the source file of the testcase, it sees a `config/2` macro while the actual definition is this:
```
-define(config,test_server:lookup_config).
```
It doesn't even look like a "function" definition for the parser.

**To Reproduce**

Check out e.g. the `els_formatter_SUITE` module, it uses the `?config` macro.

**Expected behavior**

I expected `erlang_ls` to find the `?config` macro.

**Actual behavior**

The macro is not found.

**Context**
 - `erlang_ls` version (tag/sha): c42f6dd05c3802a254e0a67c1f4158f3e63539af
 - Editor used: vim
 - LSP client used: CoC

**Comment by gomoripeti** [comment]
(If I remember correctly) erlang_ls tries to move away from the ?config macro as it's not much different from a simple `proplists:get_value`.

But this does not help other projects using such ambiguous macros. Is there any other erlang_ls feature apart from goto-definition where a workaround can be applied? (eg find-references still won't work I guess.)

I don't think this issue can be addressed in the parser as it does not know about the set of defined macros.

**Comment by NAR** [comment]
My solution (see #1074 ) modifies the code navigator. This also solves the "unused include" problem.

**Comment by robertoaloi** [comment]
> (If I remember correctly) erlang_ls tries to move away from the ?config macro as it's not much different from a simple proplists:get_value.

I don't recall a discussion around the usage of `?config`.
