### ISSUE TITLE
Code Lens for including a header file when auto-completing an imported record name.

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#108]
When pressing the '#' character, record names will be suggested for auto-complete (see #92 ). Whenever a record defined in a non-included header file is picked, a code lens should propose the user to include the header file.

**Comment by alanz** [comment]
I think this is probably better done with a code action.

**Comment by alanz** [comment]
The original intent of this issue can be achieved by returning a value for the `additionalTextEdits?: TextEdit[];` field of the returned `CompletionItem`.

**Comment by plux** [comment]
Added a code action to accomplish this:
https://github.com/erlang-ls/erlang_ls/pull/1510
