### ISSUE TITLE
Can't attach to epmd

### ISSUE THREAD

**Issue by Zabrane** [erlang-ls/erlang_ls#1089]
I'm unable to connect to [epmd](https://erlang-ls.github.io/troubleshooting/):

```bash
$ rebar3 version
rebar 3.15.1 on Erlang/OTP 24 Erts 12.0

$ erlang_ls --version                                     
Version: 0.19.0+build.1673.ref6d591a4

$ erlang_ls                                                           
Content-Length: 178

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"[2021-09-21T00:40:26.400445+02:00] [info] Started erlang_ls server [erlang_ls:main/1 L28] <0.9.0>\n","type":4}}

$ epmd -names
epmd: up and running on port 4369 with data:
```

Tested with master (+ v0.19.0) under `MacOS BigSur 11.6`, `Ubuntu20.04 LTS` and `CentOS 8`.
Erlang versions: `22.2` and `24.0.6`.

Full [server.log](https://github.com/erlang-ls/erlang_ls/files/7200862/server.log) attached:
```
/Users/zab/Library/Logs/erlang_ls/tmp/server.log
```

As you can see from the logs, there's an error when starting `httpc_manager`.

**Comment by robertoaloi** [comment]
Hi @Zabrane this is not a bug. Distribution fort the server is not started during bootstrap (i.e. when you run the `erlang_ls` command), but [as a consequence](https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_general_provider.erl#L87) of the [initialized](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialized) notification that the LSP client sends to the server.

In your case, you are manually starting the server from the shell, so no client is sending the `initialized` notification. In other words, this is expected behaviour.

The line in the logs regarding `httpc_manager` looks more of a progress report rather than a crash?

**Comment by Zabrane** [comment]
Hi @robertoaloi 

Thanks for the feedback. So as long as no client connects (in my case Emacs) to it, `erlang_ls` will not attach to `EPMD`?
Is my understanding correct?

**Comment by Zabrane** [comment]
I'm using `spacemacs`  (develop branch):
```bash
ls -la ~/.emacs.d/elpa
drwxr-xr-x - zab 21 Sep 00:37 27.1
drwxr-xr-x - zab 21 Sep 00:36 develop
drwx------ - zab 21 Sep 07:57 gnupg
```

and this is my config:
```lisp
  dotspacemacs-configuration-layers
   '(
     yaml
     lua
     shell-scripts
     html
     go
     python
     c-c++
     ruby
     ;erlang
     lsp
     (erlang :variables
       erlang-backend 'lsp
       erlang-root-dir "/Users/zab/erlang/current"
       ;; erlang-man-root-dir "<path to>/otp_22_kred/lib/erlang/man"
       erlang-fill-column 100
       company-minimum-prefix-length 1
       company-idle-delay 0.3
       lsp-ui-doc-position 'bottom)
  ...
 ```
 
 Still, `epmd` shows no node connected:
 ```bash
 epmd: up and running on port 4369 with data:
 ```

**Comment by Zabrane** [comment]
@robertoaloi found and fixed the issue.

In my working environment, starting a new shell wipes out all your ENV variables, aliases...
Thus, `escript` couldn't be found.

I had to rename `erlang_ls` as `erlang_ls.escipt` and to create this shell script instead:
```bash
$ mv /usr/local/bin/erlang_ls /usr/local/bin/erlang_ls.escript
$ cat /usr/local/bin/erlang_ls
#!/bin/sh
exec /Users/zab/erlang/current/bin/escript /usr/local/bin/erlang_ls.escript
$ chmod +x /usr/local/bin/erlang_ls
```
One more thing: i'm mainly using Emacs without GUI (`emacsclient`). Do you face any issue whith the combo `emacsclient` and `erlang_ls`? I'm asking because I can see a lot of disconnections from `erlang_ls` in Emacs buffer.

**Comment by Zabrane** [comment]
@robertoaloi does it make sense to you?

<img width="581" alt="Screenshot 2021-09-21 at 22 36 55" src="https://user-images.githubusercontent.com/532544/134244028-8a651dd9-643f-406d-b6c1-32b1917cfe49.png">

My project is a valid Erlang project with `src`, `include`... dirs.

**Comment by Zabrane** [comment]
Re-compiling Erlang27 with [Jansson](https://github.com/akheron/jansson) (JSON C lib) solved this issue.
