### ISSUE TITLE
make hover for functions faster

### ISSUE THREAD

**Issue by TheGeorge** [erlang-ls/erlang_ls#1093]
**Is your feature request related to a problem? Please describe.**
As discovered when working on #1092 hover is currently slow on large modules' functions, taking up to 10 seconds

This severely limits the usability component of this feature, and we should aim to bring this down to a second

**Comment by TheGeorge** [comment]
The issue is that the call 
https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_docs.erl#L214
takes long to return for large modules, because the whole module is parsed every time (there is no caching)

So one option could be to have an additional DB/ETS that indexes edoc documentation

**Comment by robertoaloi** [comment]
@TheGeorge Should we mark this as done or are you looking into caching?

**Comment by TheGeorge** [comment]
This is done, caching should be another issue
