### ISSUE TITLE
The `erlang_ls.config` file should expand environment variables.

### ISSUE THREAD

**Issue by fmv1992** [erlang-ls/erlang_ls#1121]
**Describe the bug**
The `erlang_ls.config` file should expand environment variables.

**To Reproduce**

```
# https://erlang-ls.github.io/configuration/

include_dirs:
  - "$HOME/bin/erlang/"
```

Does not work. But:

```
include_dirs:
  - "/home/myuser/bin/erlang/"
```

Does.

**Expected behavior**
I expected `- "$HOME/bin/erlang/"` would be properly expanded.

**Actual behavior**
The `$HOME` environment variable does not get expanded.

**Context**
 - `erlang_ls` version (tag/sha): `[coc.nvim] Erlang LS version: 0.20.0+build.1690.ref51a48ef, OTP version: 24`.
 - Editor used: vim.
 - LSP client used: coc.nvim

**Comment by NobbZ** [comment]
Supporting this would be a game changer for NixOS users as well.

The location of my erlang binary, its modules and basically anything changes every other day when I enter the project specific environment.

Without being able to make the ELS aware of the ever changing environment I either have to constantly update the configuration file or alternatively miss many features of the LSP.
