### ISSUE TITLE
Hovering over os:cmd/1 causes a server crash

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#1145]
Simply add a `os:cmd("uname -a")` and hover over it. You will notice a crash in both Emacs and VS Code.

Git bisect shows this as the culprit: a84d93fb87f64765f29e2f564490aa8bc3a03d1f

@garazdawi FYI

**Comment by garazdawi** [comment]
Uhm, how odd. For all versions of erlang?

I'll take a look tomorrow if you don't have time before then.

**Comment by garazdawi** [comment]
The unicode support was not enabled at all for stdout, so any documentation with unicode symbols did not work. `os:cmd` was rendered with `&npsp;` which is why it triggered the fault.

Fixed in #1147 together with some aesthetic fixes for `os:cmd`.
