### ISSUE TITLE
Module file name mismatch compiler error not exposed

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#1152]
**Describe the bug**
A module with a name not matching the file name does issue an error.

**To Reproduce**
Create a module in the file `foo.erl`:
```
-module(bar).
```

**Expected behavior**
An error similar to the Erlang compilation error should be issued:
```
$ erlc foo.erl
/path/to/foo.beam: Module name 'bar' does not match file name 'foo'
```

**Actual behavior**
No error is visible.

**Context**
 - `erlang_ls` version (tag/sha): 0.21.1
 - Editor used: Sublime Text 4 (4122)
 - LSP client used: Sublime LSP v1.14.0

**Comment by robertoaloi** [comment]
Interesting, thanks for the report. I never noticed this since Emacs' Erlang mode already prevents that.
The fact that the error is not visible is due to the `basic_validation` parameter which is passed to `compile:file/2`. Even the  `strong_validation` doesn't seem to help.

**Comment by robertoaloi** [comment]
Confirmed from the code in OTP. The error is only emitted if a binary is saved, which doesn't happen in the case of `basic_validation` or `strong_validation`. I guess we can replicate the check from Erlang LS side.

**Comment by eproxus** [comment]
Should this be a "bug" report to OTP, in that the compiler doesn't validate this? I assume it's hard coded somewhere else in the Erlang compiler stack then, because `erlc` generates the error...

I guess it's not strictly seen as an error, because you can produce beam files with whatever `-module(Name)` attribute you want, and they only fail when you actually load them?
