### ISSUE TITLE
ErlangLS ignores snippetSupport capability

### ISSUE THREAD

**Issue by sirikid** [erlang-ls/erlang_ls#1169]
https://github.com/erlang-ls/erlang_ls/blob/3902e3e842cfd4103c08618e83ea18928c49cdc0/apps/els_core/include/els_core.hrl#L354

Server was started with `snippetSupport = false`, but I still get snippets instead of plain text.

![image](https://user-images.githubusercontent.com/4840430/148658559-449d624c-bb4f-441b-90fe-06ae1156e771.png)

**Comment by robertoaloi** [comment]
Thanks for reporting!
