### ISSUE TITLE
Keymap prefix needs to be set before loading lsp-mode

### ISSUE THREAD

**Issue by richcarl** [erlang-ls/erlang_ls#1174]
https://github.com/erlang-ls/erlang_ls/blob/b3ce352f92f01554b25920c8a6e3b582fefe9954/misc/dotemacs#L30

If lsp-keymap-prefix is set after lsp-mode is loaded, it doesn't actually affect the key binding.
From https://emacs-lsp.github.io/lsp-mode/page/installation/:
```
;; if you want to change prefix for lsp-mode keybindings.
(setq lsp-keymap-prefix "s-l")

(require 'lsp-mode)
(add-hook 'XXX-mode-hook #'lsp)
```

**Comment by robertoaloi** [comment]
Thanks for reporting @richcarl . I swapped the order of the two expressions in #1175 , feel free to have a look!
