### ISSUE TITLE
Troubles with open telemetry macros on VSCode

### ISSUE THREAD

**Issue by mcesaro** [erlang-ls/erlang_ls#1179]
**Describe the bug**
Likely related to #762: 
Including the open tracer macro definitions triggers a false positive error.
Although `erlang_ls` reports an "undefined macro" error, the macro definition is actually found correct:

![els_macro](https://user-images.githubusercontent.com/6418086/150742614-901971c2-1771-4446-b8c3-69b87506d8ee.png)

**To Reproduce**
Just include the `otel_tracer.hrl` file:

![els_macro_2](https://user-images.githubusercontent.com/6418086/150743627-97d5fa21-5db1-445b-9697-4b0a51a27c17.png)

The the projects compiles and runs fine.

**Expected behavior**
No errors reported.
Note: the `erlang_ls` log reports no errors.

**Actual behavior**
The VSCode plugin reports an error for the include statement and errors on any function using the  `?with_span` macro.

**Context**
 - `erlang_ls` version (tag/sha): Erlang LS  version: 0.21.2, OTP version: 24
 - Editor used: VS Code
 - LSP client used:

The `include` configuration:
```yaml
include_dirs:
  - "include"
  - "_build/default/lib/*/include"
  - "_build/default/lib/opentelemetry_api/apps/*/include"
  - "_build/default/lib/opentelemetry_api/apps/opentelemetry_api/include"
```

**Comment by AminArria** [comment]
@mcesaro try adding `_build/default/lib` to your `include_dirs` config

**Comment by mcesaro** [comment]
> @mcesaro try adding `_build/default/lib` to your `include_dirs` config
Hi,
I tried, but the problem persists.
Thanks

**Comment by mcesaro** [comment]
Just for the record, the issue is fixed by adding
```yaml
  - "_build/default/lib/opentelemetry_api/apps/opentelemetry_api/include"
```
and including the `otel_tracer.hrl` file without an explicit path:

```erlang
-include_lib("otel_tracer.hrl").
```

to the config file.
