### ISSUE TITLE
Rename on a variable renames variables in a following spec

### ISSUE THREAD

**Issue by michalmuskala** [erlang-ls/erlang_ls#1180]
**Describe the bug**
Given this code:
```erl
foo(A) -> A.

-spec bar(A :: integer()) -> integer().
bar(A) -> A.
```
Using the "Rename" command with text "B" on either of the `A` variables in `foo` produces:
```erl
foo(B) -> B.

-spec bar(B :: integer()) -> integer().
bar(A) -> A.
```

**Expected behavior**

It should not touch the spec and produce:
```erl
foo(B) -> B.

-spec bar(A :: integer()) -> integer().
bar(A) -> A.
```

**Context**
 - `erlang_ls` version (tag/sha): Last release (Erlang LS (in erlang_ls), version: 0.21.2, OTP version: 24)
 - Editor used: VS Code

**Comment by gomoripeti** [comment]
thanks Michal for the report. Indeed the heuristic to find the scope of the variable needs to be improved. (Currently it assumes the scope is a function clause and to find the end it takes the next function clause after the variable https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_rename_provider.erl#L231)
