### ISSUE TITLE
Renaming a spec should rename the function

### ISSUE THREAD

**Issue by michalmuskala** [erlang-ls/erlang_ls#1189]
**Is your feature request related to a problem? Please describe.**

Renaming a function works, when the cursor is placed on one of the function heads. The same should work, if the cursor is placed on the spec attached to the function.

Renaming the function already correctly renames the spec.

The attached video shows first attempting to rename a spec. which fails, and then successfully renaming the function.

https://user-images.githubusercontent.com/477062/152157419-1266fb90-0cd7-415f-8e09-2edf03dd9388.mov

**Comment by plux** [comment]
Easy fix :+1:
