### ISSUE TITLE
Add Code Action / Quick Fix to rename an incorrectly named module

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#1207]
# Context

One of the core features of Erlang LS is to be able to publish a [diagnostic message](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics) whenever an issue is detected in the user code. Diagnostics are often rendered by the IDE with a _squiggle_ of different colour, depending on the severity of the message (e.g. a _warning_ uses a yellow squiggle, while an _error_ uses a red squiggle).

One of these messages is displayed whenever [a module attribute contains a name which does not match the file name](https://www.erlang.org/doc/reference_manual/modules.html#pre-defined-module-attributes). See the picture below.

<img width="1485" alt="Screenshot 2022-02-17 at 09 08 11" src="https://user-images.githubusercontent.com/91769/154432444-5dc3e8ed-8eb7-49d7-9b4d-e930e7af35ed.png">

A [Code Action request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) is sent from the IDE to the language server to compute the possible [code actions](https://code.visualstudio.com/docs/editor/refactoring) available for a given document and text range. In the case above, the following request is sent from the IDE to the language server as soon as the user hovers the incorrect module name.

```
[Trace - 09:08:14 AM] Sending request 'textDocument/codeAction - (5913)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/robertoaloi/git/github/erlang-ls/erlang_ls/apps/els_lsp/src/els_background_job.erl"
  },
  "range": {
    "start": {
      "line": 3,
      "character": 9
    },
    "end": {
      "line": 3,
      "character": 9
    }
  },
  "context": {
    "diagnostics": [
      {
        "source": "Compiler (via Erlang LS)",
        "severity": 1,
        "range": {
          "start": {
            "line": 3,
            "character": 8
          },
          "end": {
            "line": 3,
            "character": 18
          }
        },
        "message": "Module name 'els_bg_job' does not match file name 'els_background_job'"
      }
    ]
  }
}

[Trace - 09:08:14 AM] Received response 'textDocument/codeAction - (5913)' in 77ms.
Result: []
```

As you can see, the request contains the current location (file path, line number, line column) and an additional _context_ (in this case a list containing one diagnostic, which can in turn be used by the server to provide a list of available code actions. Right now, since this feature is not yet implemented, no code actions (i.e. an empty list or `[]`) is returned to the client.

# What is Required

In case a `textDocument/codeAction` request is received by the language server, the server should check for presence of "Module name mismatch" diagnostics. If one is present, the server should include two code actions (say `rename-module` and `rename-file`) in the response.

Once the possible code action is received by the IDE, the user gets notified. This usually happens via a little bulb icon or similar, which suggests that a code action is available. In this case, the code actions would be of type _quickfix_ and suggest to either rename the module or the file, to ensure they match.

# Code Pointers

* Code action requests are dispatched to the `els_code_action_provider` module, so you probably want to start there

# Testing

Don't forget to include a test for the new functionality! You can look at existing examples in the `els_code_action_SUITE` module and at this [code lenses tutorial](https://erlang-ls.github.io/articles/tutorial-code-lenses) which includes a [testing overview](https://erlang-ls.github.io/articles/tutorial-code-lenses/#adding-tests) which also applies to code actions.

# Problems following the instructions?

[Get in touch](https://erlang-ls.github.io/#get-in-touch)! We'll be glad to help you to get unblocked and to improve our docs.

**Comment by robertoaloi** [comment]
FYI @plux . I created a number of "code action" tickets for newcomers, based on the same template. Feel free to add more using the same template, if you have any ideas.

**Comment by plux** [comment]
> FYI @plux . I created a number of "code action" tickets for newcomers, based on the same template. Feel free to add more using the same template, if you have any ideas.

Nice idea!
