### ISSUE TITLE
erlang_ls does not index subdirectories of `src/` on startup

### ISSUE THREAD

**Issue by barndon** [erlang-ls/erlang_ls#1269]
**Describe the bug**
erlang_ls does not index all files in subdirectories of `src` on startup.  

**To Reproduce**

1. `git clone https://github.com/barndon/fiddle`
2. `cd fiddle`
3. Open `src/widgets/alpha_widget.erl` in an erlang_ls-enabled editor.  (Emacs, in my case.)
4. Ask the editor to find references to alpha_widget's init/0 function.  Observe that none can be found. (This is incorrect.)
5. Connect to the running erlang_ls instance via `erl -remsh`; inspect the `els_dt_document_index` ETS table and observe that the only file in `src/widgets` that has been indexed at this point is `alpha_widget.erl`.  Here is a one-liner that may help (adjust the path to the `fiddle` directory to match your filesystem):

``` erlang
lists:filter(fun ([<<"file:///path/to/fiddle/", _Rest/binary>>]) -> true; (_) -> false end, ets:match(els_dt_document_index, {'_', '_', '$1', module})).
```

On my system, this one-liner yields:

``` erlang
[[<<"file:///home/barndon/src/erlang/fiddle/src/widgets/alpha_widget.erl">>],
 [<<"file:///home/barndon/src/erlang/fiddle/src/fiddle.erl">>],
 [<<"file:///home/barndon/src/erlang/fiddle/src/fiddle_sup.erl">>],
 [<<"file:///home/barndon/src/erlang/fiddle/src/fiddle_app.erl">>]]
```

**Expected behavior**
One reference to `alpha_widget:init/0` in `src/widgets/beta_widget.erl` should be found.

**Actual behavior**
Zero references to `alpha_widget:init/0` are found.

**Context**
 - `erlang_ls` version (tag/sha):  ad06727867fb33db87d543ac464d3293992b401b (Version: 0.27.0+build.1833.refad06727)
 - Editor used: Emacs 27.1
 - LSP client used: lsp-mode 8.0.1

**Comment by plux** [comment]
This was fixed by https://github.com/erlang-ls/erlang_ls/pull/1459
