### ISSUE TITLE
The "create function" code action can produce code in the incorrect place.

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#1280]
The code action takes the end location of the _last_ POI. This is not guaranteed the one with the widest range (e.g. it could be an atom within the last function). Instead, we could consider the folding range of the last "function" POI.

**Comment by michalmuskala** [comment]
An alternative would be to generate it right after the function with the error - this might be a simpler logic (and it doesn't require loading the entire world).
