### ISSUE TITLE
Doesn't autocomplete and crashing 

### ISSUE THREAD

**Issue by itsdend** [erlang-ls/erlang_ls#1294]
**Describe the bug**
Extension is not offering autocomplete, instead the requests sent to the server are failing and the server crashes, and after 5 times it is not restarting.
I am not using erlang-ls server downloaded with extension because with default server it wont even start.

**To Reproduce**
example 1 ->
writing io:
pressing: "ctrl + space" to open offered functions in that module in search of format/3

(it doesn't have to be io module, it can be what ever module);

example 2 ->
typing literally anything

**Expected behavior**
When writing I am expecting, autocomplete options

**Actual behavior**
When writing "io:" in autocomplete box it just says loading and nothing happens, requests are sent to the server but it just fails.
In output I am getting this error:
 
  "Request textDocument/completion failed.
     Message: Unexpected error while textDocument/completion
     Code: -32001"

This happens whenever I type anything, like variable name or writing my own new function.
After a couple of seconds into writing code, everything crashes.

**Context**
 - `erlang_ls` version (tag/sha):  0.32.0+build.1856.refcfab726
 - Editor used: vscode
 - LSP client used: erlang-ls
 - OS: Windows

**Comment by robertoaloi** [comment]
Hi @itsdend and thanks for reporting. Could you please attach your `server.log` file (or an obfuscated extract if you prefer), so that we can pinpoint the root cause? The location of the log files is described [here](https://erlang-ls.github.io/troubleshooting/#logging).

**Comment by itsdend** [comment]
hI,
Here is the full error report on two example
[server.log](https://github.com/erlang-ls/erlang_ls/files/8673702/server.log)
s

**Comment by robertoaloi** [comment]
Hi @itsdend . The logs highlight a text synchronization issue, but they don't show the sequence of commands that lead to them. A possibility is to raise verbosity of the logs to DEBUG, which should tell us the whole story. If I have to guess, this is probably due to the handling of `didChangeWatchedFiles`, for which support is still partial in Erlang LS (did you rebase/checkout just before getting the issue?). I will try and prioritize that.

**Comment by itsdend** [comment]
I switched to the neovim in the meantime and had similar issues, like connection with erlang_ls just crashing.
So I uninstalled erlang_ls and rebar3 because issue was somewhere in there. It looks like I installed both of them in normal mode through powershell, so I open powershell in administrator mode and tried that again and now everything is working normally.
So I'll just close the issue.

I'll just post here the error I had when I cloned the erlang_ls repository and called 'make' command through powershell in normal mode for future references. (Admin mode had no errors)
Error >>
"Building escript..."
===> Fetching erlfmt v1.0.0
===> Errors loading plugin erlfmt. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_proper v0.12.1
===> Errors loading plugin rebar3_proper. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching coveralls v2.2.0
===> Errors loading plugin coveralls. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_lint v1.0.2
===> Errors loading plugin rebar3_lint. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_bsp (from {git,"https://github.com/erlang-ls/rebar3_bsp.git",
                      {ref,"master"}})
===> Errors loading plugin {rebar3_bsp,
                               {git,
                                   "https://github.com/erlang-ls/rebar3_bsp.git",
                                   {ref,"master"}}}. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_proper v0.12.1
===> Errors loading plugin rebar3_proper. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching coveralls v2.2.0
===> Errors loading plugin coveralls. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_lint v1.0.2
===> Errors loading plugin rebar3_lint. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching rebar3_bsp (from {git,"https://github.com/erlang-ls/rebar3_bsp.git",
                      {ref,"master"}})
===> Errors loading plugin {rebar3_bsp,
                               {git,
                                   "https://github.com/erlang-ls/rebar3_bsp.git",
                                   {ref,"master"}}}. Run rebar3 with DEBUG=1 set to see errors.
===> Verifying dependencies...
===> Fetching docsh v0.7.2
===> Dependency failure: source for docsh does not contain a recognizable project and can not be built
make: *** [all]
