### ISSUE TITLE
Unexpected errors on didOpen and didChange, LSP entirely not working.

### ISSUE THREAD

**Issue by AlexSWall** [erlang-ls/erlang_ls#1296]
**Describe the bug**
Starting my text editor (neovim) with the LSP attached immediately gives me an error of the form
```
LSP[erlangls]: Error INVALID_SERVER_MESSAGE: {
  error = {
    code = -32001,
    message = "Unexpected error while textDocument/didOpen"
  },
  jsonrpc = "2.0"
}
```
and I get the same but with `didChange` instead of `didOpen` on typing anything. Every other LSP is working with the same setup so I believe it to be specific to erlang_ls.

**To Reproduce**
I am simply opening the text editor with the LSP attached.

**Context**
 - `erlang_ls` version (tag/sha): `cfab726`
 - Editor used: neovim v0.7 (on Ubuntu 18.04).
 - LSP client used: nvim-lspconfig (latest)

[You can see my server.log here.](https://github.com/erlang-ls/erlang_ls/files/8674291/server.log)

**Comment by robertoaloi** [comment]
What I think is happening is that the IDE is sending a `didOpen` request for a file which is not (yet?) readable from disk. I checked [the specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen) and they are very clear in the sense that the language server should not try to access the file from disk:

> The server must not try to read the document’s content using the document’s Uri.

Erlang LS erroneously does that. I will prepare a fix and ping you once it's available, so you can try if it works.

Thanks for reporting @AlexSWall !
