### ISSUE TITLE
implement textDocument/signatureHelp

### ISSUE THREAD

**Issue by the-mikedavis** [erlang-ls/erlang_ls#1300]
**Is your feature request related to a problem? Please describe.**

Signature help is a very cool feature from the LSP spec. It provides documentation as you write the arguments of a function call and highlights the active parameter as you type.

**Describe the solution you'd like**

It looks like this would need a new provider module `els_signature_help_provider` which could re-use some of the machinery from `els_completion_provider` to determine docs. I think we can determine the active signature by scanning backwards in the `els_text:tokens/1` potentially across multiple `els_text:line/3`s (function calls may spread across lines unlike completions).

A good first iteration for this would be to add signature help for functions but it could be extended to support macros and types as well.

**Describe alternatives you've considered**

Snippets could be seen as competing with signature help, but IMO the two features complement each other since signature help keeps the documentation for the function call open. My editor doesn't support snippets yet and I think it might be easier to implement signature help here 😅

**Additional context**

`textDocument/signatureHelp` in the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp

An example with `rust-analyzer` from [helix-editor/helix#1755](https://github.com/helix-editor/helix/pull/1755):

<img src="https://user-images.githubusercontent.com/23398472/156893257-698b2c1b-9172-4e45-b2da-d149be3df356.gif" alt="command" width="500"/>

With ElixirLS:

[![asciicast](https://asciinema.org/a/494420.svg)](https://asciinema.org/a/494420)

**Comment by the-mikedavis** [comment]
I would like to work on this if you would be interested in accepting a contribution for it.

I think the only tricky part is detecting the current signature since one of the trigger characters (`(`, `,`, and maybe `)`) shows up very often outside of signatures: `,`. I'll play around with it and see if I can come up with something robust.

**Comment by robertoaloi** [comment]
Hi @the-mikedavis , absolutely! Adding support for this would be great, feel free to help out and to reach out if you need help!
