### ISSUE TITLE
Be able to list all modules / search for a module in a workspace

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#134]

**Comment by robertoaloi** [comment]
It turns out that `documentSymbol` is only supposed to return symbols belonging to the same document (it's obvious once you know it), so I am implementing this as part of `workspace/symbol`, instead.

**Comment by jfacorro** [comment]
How can this be used from Emacs?

**Comment by robertoaloi** [comment]
I use it with:

`M-x lsp-ui-find-workspace-symbol`
(requires `lsp-ui`, of course you can bind a key combination to it)

Then:

`m` -> get all modules
`m_MODULE` -> jumps to MODULE

The upcoming version of the LSP protocol (3.15) makes this a lot nicer and more powerful. See https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_symbol

Created #155 as a follow-up.

**Comment by jfacorro** [comment]
I discovered today that the `helm-lsp` mode provide a nicer interface to this feature, see the comment in #181.
