### ISSUE TITLE
can not find any otp modules in fedora 36

### ISSUE THREAD

**Issue by KunaPrime** [erlang-ls/erlang_ls#1348]
Hi, 

i'm using fedora 36, nvim-lsp
have installed erlang_ls from source
installed erlang with `dnf install erlang` 

erlang_ls cannot find any module from otp relase (under /usr/lib64/eralng) 
the same configuration (other than `otp_path`) is working under the ubuntu

**Comment by vihu** [comment]
May not be an ideal solution but can you also try removing packaged erlang and reinstalling via [asdf](https://asdf-vm.com/guide/getting-started.html). The only reason I say is because I am on the exact same setup and asdf erlang works just fine (as long as you source the right paths).

**Comment by KunaPrime** [comment]
@vihu thank you for your suggestion. With `asdf` everything works as expected but I feel this is more like a workaround than a solution so I'm leaving this issue open.

**Comment by robertoaloi** [comment]
Hi @KunaPrime , could you run `tree` in both installation directories and show which `otp_path` are you setting in the config in both cases?

**Comment by DavidAlphaFox** [comment]
I think this bug is caused by Fedora's Erlang package. Fedora delete all the sources code of OTP's library when they release the package.
Because the erlang_ls can't find the source code of library, the erlang_ls can't promote any module in Emacs or Vim.
