### ISSUE TITLE
Support field name completion inside curly brackets of records

### ISSUE THREAD

**Issue by edvreu** [erlang-ls/erlang_ls#1360]
**Is your feature request related to a problem? Please describe.**
Working with records is not great. To get the field names for a record you have to hover the record and copy the fields from the pop-up box.

**Describe the solution you'd like**
When the cursor is inside the curly brackets of a record and triggering suggestion the field names of the record shows up.

**Describe alternatives you've considered**
I know typing `#record_name.` will show me the field names, but that can never replace getting them inside curly brackets.

**Comment by robertoaloi** [comment]
This should definitely be doable. We could start by adding `{` and maybe `,` as trigger characters and use an approach similar to:

https://github.com/erlang-ls/erlang_ls/blob/1d8500819002fa1a2d1969619dbbc99ca91409de/apps/els_lsp/src/els_completion_provider.erl#L171

**Comment by edvreu** [comment]
I have been trying to solve this. I was trying to use the `record_expr` POI, however the range of this POI is from `#` to end of the record name. Is it a good first step to change the range to be from `#` to either `.` or the closing bracket `}` (this also has to handle nested records), or does this brake rename for records?
