### ISSUE TITLE
Need Custom Node Name / Host Name / Domain Name

### ISSUE THREAD

**Issue by zachlankton** [erlang-ls/erlang_ls#1371]
I need the ability to set a custom hostname/domain name, especially when long names are used.  

Currently, the code gets the hostname from `inet` module in the code below.

https://github.com/erlang-ls/erlang_ls/blob/2dfb48aca3879e5b44f6fd676f8349525262779f/apps/els_core/src/els_distribution_server.erl#L226-L227

Additionally, if `longnames` are used, then the following code also looks for a domain name:

https://github.com/erlang-ls/erlang_ls/blob/6ec94072f5b9bb984da1026f9ba0efaa072271b7/apps/els_core/src/els_distribution_server.erl#L232-L234

---

If there is no domain set, then a `.` (Dot) is added to the end of the default system hostname.  This can be seen in the server log:

```log
 [info] Distribution enabled [name='erlang_ls_couchdb_101062988@couchdbasdf.'] [els_distribution_server:start_distribution/4 L81] <0.147.0>
 [info] Started distribution for: ['erlang_ls_couchdb_101062988@couchdbasdf.'] [els_general_provider:handle_request/1 L94] <0.147.0>
```

 This results in broken commucation between the nodes, for example:

```bash
root@couchdbasdf:/workspaces/couchdb# epmd -names
epmd: up and running on port 4369 with data:
name remsh3950 at port 35375
name node3 at port 37055
name node1 at port 45007
name node2 at port 43553
name erlang_ls_dap_couchdb_61071580 at port 33395
name erlang_ls_couchdb_101062988 at port 42991

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988@couchdbasdf.
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***

----- OR Without the Dot at the end ------

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988@couchdbasdf 
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***
=ERROR REPORT==== 28-Aug-2022::23:51:43.999881 ===
** System running to use fully qualified hostnames **
** Hostname couchdbasdf is illegal **

----- OR without the hostname entirely -----

root@couchdbasdf:/workspaces/couchdb# erl -name test@127.0.0.1 -remsh erlang_ls_couchdb_101062988             
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

*** ERROR: Shell process terminated! (^G to start new job) ***

----- OR From the project node ------

Eshell V13.0.4  (abort with ^G)
(node1@127.0.0.1)1> net_adm:ping('erlang_ls_couchdb_101062988@couchdbasdf.').
pang
(node1@127.0.0.1)2> net_adm:ping('erlang_ls_couchdb_101062988@couchdbasdf'). 
pang
(node1@127.0.0.1)3> net_adm:ping('erlang_ls_couchdb_101062988').            
pang
(node1@127.0.0.1)4> 
```

Because of the above, I have to do some really hacky things to get my setup to work.

Current Setup:
- VSCode
- DevContainer (in Docker)
- Erlang Ls extension
- Apache/CouchDB codebase

The CouchDB code base has a boot strap type dev script that spins up a cluster with 3 nodes that are named `node{1-3}@127.0.0.1` using longnames.  This can be seen in the output of `epmd -names` shown above.

In order to get communication between nodes, code_reloading and debugging to work I have to set the hostname to `127` and include an `erl_inetrc` file that contains the following:

```erlang
%% -- ERLANG INET CONFIGURATION FILE --
{domain, "0.0.1"}.
```

My erlang_ls.config file looks like this:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127"   # <-- the ".0.0.1" gets added by els_utils:compose_node_name because of using longnames
runtime:
    use_long_names: true
```

My `launch.json` file looks like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start Dev w/ Debug",
            "use_long_names": true,
            "type": "erlang",
            "request": "launch",
            "runinterminal": [
                "./dev/run",
                "--with-admin-party-please",
                "--no-eval",
                "dev/remsh"
            ],
            "projectnode": "node1@127.0.0.1",
            "timeout": 300,
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

---

# Proposal

I believe all this heart ache could be relieved if there was a custom `hostname` option for the `erlang_ls.config` file.

Additionally, I am curious if it is truly intended for the `code_reload: node:` setting to be modified at all?  It seems more natural to specify exactly the node to connect to for code reloading than to have to remember that the hostname/domain will get appended.  Is there a reason the code looks at the node name and modifies it?

For example:

```yaml
apps_dirs:
    - "src/*"
include_dirs:
    - "src"
    - "src/*/include"
code_reload:
    node: "node1@127.0.0.1"   <--- remove the code that modifies this node name in els_utils:compose_node_name
runtime:
    use_long_names: true
hostname: "127.0.0.1"
```

and then update the `els_distribution_server` with something like this?

```diff
node_name(Prefix, Name0) ->
+   CustomHostname = els_config:get(hostname),
+   case CustomHostname of
+       undefined ->
            Name = normalize_node_name(Name0),
            Int = erlang:phash2(erlang:timestamp()),
            Id = lists:flatten(io_lib:format("~s_~s_~p", [Prefix, Name, Int])),
            {ok, HostName} = inet:gethostname(),
            node_name(Id, HostName, els_config_runtime:get_name_type());
+       _ -> CustomHostname
+   end.
```

Those more familiar with this project and code base may know more and be able to offer better suggestions/thoughts/feedback.

Thank you.

**Comment by robertoaloi** [comment]
Hi @zachlankton and thanks for the detailed issue and proposal. I don't think there's a special reason for this, other than the majority of Erlang LS users (including myself) use short names and therefore never encountered the issue.
In my mind it makes sense to simplify the config so that users don't have to figure how a tricky config that works by accident. Explicit is better.

We may still want to ensure a unique name for the node, since multiple instances of Erlang LS could run at the same time for the project (imagine opening Emacs and VS Code on the same project). Having a hard-coded hostname (in the case one is specified in the config) may result in the second instance failing to start, so we may want to preserve the phash2 part in the case a custom hostname is provided.

We could also refine the `node_name/3` function by:

* not blindly appending an empty domain
* take into account that the hostname could be a fully qualified name (or providing these options directly as part of the `runtime` config - eg the domain)

Would you be comfortable raising a PR based on the above? Then we can discuss the details as part of that.

@zsoci FYI since you were the one originally contributing support for longnames.

**Comment by robertoaloi** [comment]
A good idea would be to introduce some unit tests that read the config values and spit out the final node names for the project and the reload (no need to start distribution, which could be tricky in CI). That way, we would have a clear agreement on what users should expect and avoid regressions.

**Comment by zachlankton** [comment]
Ah, yeah, totally agree with the phash2 and I realize now that in my haste my proposed code above is broken.  Really all I want is to be able to specify a custom hostname.  

This code is closer to my intention: (Still may need tweaking)

```diff
node_name(Prefix, Name0) ->
    Name = normalize_node_name(Name0),
    Int = erlang:phash2(erlang:timestamp()),
    Id = lists:flatten(io_lib:format("~s_~s_~p", [Prefix, Name, Int])),
+   CustomHostname = els_config:get(hostname),
+   case CustomHostname of
+       undefined ->
            {ok, HostName} = inet:gethostname(),
            node_name(Id, HostName, els_config_runtime:get_name_type());
+       _ -> node_name(Id, CustomHostName, shortnames);
+   end.
```

**Comment by zachlankton** [comment]
I can start working on a PR to flesh out the details.

**Comment by zsoci** [comment]
@robertoaloi thanks for the heads up. I agree with your proposal above. So instead of hostname config value, I would introduce the 'domain' config value that in case exist and we use long names (use_long_names = true) we append it from the config. If it is undefined, we try to get it from inet:get_rc() and in case it is not empty, we append . ++ DomainName.
