### ISSUE TITLE
DAP crashes when a breakpoint is set on an unavailable module

### ISSUE THREAD

**Issue by TheGeorge** [erlang-ls/erlang_ls#1373]
**Describe the bug**
DAP crashes when a breakpoint is set on a module that is not availabe in the node that is debugged
**To Reproduce**
open a module that is not available in the node, and set a breakpoint

**Expected behavior**
Error message or something

**Actual behavior**
DAP crashes silently

**Comment by robertoaloi** [comment]
@TheGeorge Do we want to try and load the module if it's not loaded? This is probably happening [here](https://github.com/erlang-ls/erlang_ls/blob/4afd02260026295d9b8de7fda022e24eb2850089/apps/els_dap/src/els_dap_general_provider.erl#L195).

**Comment by TheGeorge** [comment]
Yeah, I'm working an a fix
