### ISSUE TITLE
.erlang.cookie directory disable

### ISSUE THREAD

**Issue by ignamartinoli** [erlang-ls/erlang_ls#1375]
**Is your feature request related to a problem? Please describe.**

Every time I use `erlang_ls`, a directory called `.erlang.cookie` gets created in `$HOME`.
I try to keep my `$HOME` directory clean, so it's a bit annoying.

**Describe the solution you'd like**

It would be cool to be able to disable the directory creation or at least choose were it's created with an environment variable (`$XDG_CACHE_HOME` perhaps).

**Additional context**

I use `erlang_ls` with **Neovim**' and `nvim-lspconfig`.

**Comment by TheGeorge** [comment]
Hi @ignamartinoli,
the `.erlang.cookie` file get's automatically generated by the Erlang runtime system on dist startup if the file does not exist.

It get's generated in the users home directory.

> The first action of the Erlang network authentication server (auth) is then to search for a file named .erlang.cookie in the [user's home directory](https://www.erlang.org/doc/man/init.html#home) and then in [filename:basedir(user_config, "erlang")](https://www.erlang.org/doc/man/filename.html#user_config). If none of the files exist, a .erlang.cooke file is created in the user's home directory.

 Please check https://www.erlang.org/doc/reference_manual/distributed.html#security for more details. 

To avoid having the file being generated in `HOME`, the easiest way would be to just mode the cookie to your config dir. You can figure out where to place it by running:
```
$ erl
..
1> filename:basedir(user_config, "erlang").
```
(for me on linux this is `~/.config/erlang`)

**Comment by ignamartinoli** [comment]
Thanks! I couldn't find documentation about it
