### ISSUE TITLE
Test and Document Language Server Usage from IntelliJ

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#14]
So far, I have been interactive with the Erlang LS via Emacs. We should test (and document) its usage from IntelliJ as well, to ensure that the server works correctly independently from the editor.

**Comment by jfacorro** [comment]
There is no IntelliJ client complete enough that I could find. The [LSP Support](https://plugins.jetbrains.com/plugin/10209-lsp-support?_ga=2.93951005.1439217459.1571558133-1891303514.1571558133) plugin one doesn't look that complete.
