### ISSUE TITLE
Which Formatter is used by ErlangLS?

### ISSUE THREAD

**Issue by mkohlhaas** [erlang-ls/erlang_ls#1438]
Just wonder which formatter is used by ErlangLS. I have integrated ErlangLS into neovim and can format code on the fly. But I would like to use the same formatter also from the command line to be consistent.

Kind regards!

**Comment by lucavallerini** [comment]
Based on `rebar.config`, it should be erlfmt by WhatsApp: https://github.com/WhatsApp/erlfmt

**Comment by filmor** [comment]
That's not true. `erlfmt` is so far (sadly) only used for parsing, formatting is done via [`rebar3_format`](https://github.com/AdRoll/rebar3_format), see https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_formatting_provider.erl#L103.
