### ISSUE TITLE
ErlangLS is using old forked version of erlfmt

### ISSUE THREAD

**Issue by ztion** [erlang-ls/erlang_ls#1451]
**Describe the bug**
ErlangLS uses erlfmt to help with parsing of erlang files. In rebar.config the erlfmt dependency is pinned to an old forked version which is behind the main branch of erlfmt.
It would be good if either this forked version could be rebased to include more recent commits, or if an effort could be made to get the code in the forked version included in the main erlfmt repo.
There is a recent commit in erlfmt which I would like to have in ErlangLS to fix a parsing issue with macros in case statements:
https://github.com/WhatsApp/erlfmt/pull/350

**Comment by plux** [comment]
This is fixed
