### ISSUE TITLE
Dialyzer diagnostics broken with OTP 26

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#1456]
The `dialyzer_plt:from_file/1` function, used by `els_typer` has been removed in https://github.com/erlang/otp/commit/963c7d5ccecb9ea4940e7112d88534781a413fa6

We should switch to the new API and ideally use Dialyzer in incremental mode.

**Comment by TD5** [comment]
I presume you could switch to [`dialyzer_cplt:from_file/1`](https://github.com/erlang/otp/blob/master/lib/dialyzer/src/dialyzer_cplt.erl#L87) as a quick fix?

**Comment by plux** [comment]
Fix for this has been merged.

Adding support for incremental dialyzer sounds like a good idea.
