### ISSUE TITLE
Logs should end up in /var/log/erlang_ls/PROJECT

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#147]
Right now it's very confusing to locate logs for a specific run. This is due to the fact logs are sparse in different dirs.

Ideally, the path should be configurable by a global `~/.config/erlang_ls` file

**Comment by robertoaloi** [comment]
@jfacorro WDYT?

**Comment by jfacorro** [comment]
It's a good step towards knowing where all the log are going 😄. Maybe it should be `/var/log/erlang_ls/PROJECT_HASH_FROM_URI` to avoid conflicts between projects with the same name but different locations.

**Comment by robertoaloi** [comment]
Then `/var/log/erlang_ls/PROJECT/HASH_FROM_URI`
