### ISSUE TITLE
Cannot find definition for function 'Mod':module_info/1

### ISSUE THREAD

**Issue by carlotm** [erlang-ls/erlang_ls#1471]
**Describe the bug**

Got `Cannot find definition for function 'Mod':module_info/1` from this snippet

```
attr(Mod, K) when is_atom(Mod) and is_atom(K) ->
    Attrs = Mod:module_info(attributes),
    proplists:get_value(K, Attrs).
```

**To Reproduce**

Just use  the [module_info/1](https://www.erlang.org/doc/reference_manual/modules#module_info-0-and-module_info-1-functions) function

**Expected behavior**

Don't get the error message

**Actual behavior**

Got `Cannot find definition for function 'Mod':module_info/1`

**Context**

 - `erlang_ls` version (tag/sha): 0.48.0
 - Editor used: vim
 - LSP client used: https://github.com/yegappan/lsp

**Comment by fridayy** [comment]
Can confirm. I reckon a possible solution could be to skip the index lookup if Mod is a variable?
```
POI  = #{data =>
           #{mod_range => #{from => {14,13},to => {14,16}},
                 name_range => #{from => {14,17},to => {14,28}},
                 fun_is_variable => false,mod_is_variable => true},
           id => {'Mod',module_info,1},
           range => #{from => {14,13},to => {14,28}},
           kind => application}.

%% els_crossref_diagnostics.erl
has_definition(#{kind := application, id := {_Module, module_info, _Arity}, data := #{mod_is_variable := true}}) -> 
    true;
```

**Comment by robertoaloi** [comment]
@fridayy the `has_definition` clause you mention is used for the "XRef-like" diagnostics. It basically means that, if the module name is a variable, the language server assumes that a definition exists and does not complain about not existing functions.

The issue that @carlotm is reporting refers to the fact that no definition is found for the `module_info/1` function. I'd say this is expected, since that function is [a special function inserted by the compiler for each module](https://www.erlang.org/doc/reference_manual/modules#module_info-0-and-module_info-1-functions). There's no place we can "jump to", so the "Cannot find definition" message seems legit. We could of course rephrase the message for those special functions.

**Comment by fridayy** [comment]
@robertoaloi thanks for the feedback!

I quickly skimmed through the code and found the `has_definition` [clause](https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_crossref_diagnostics.erl#L95) that apparently handles `module_info` for "conventional" (not passed as function args) modules and thought this could be extended to handle this case as well. :)

But I see your point, in this particular case `Mod` might not even be an actual module so I think the error is reasonable and legit or maybe a warning would be more appropriate?

**Comment by carlotm** [comment]
@robertoaloi 
Thank you. Getting an error for valid code is a bit odd IMHO, but whatever... I'll live with it

**Comment by robertoaloi** [comment]
@carlotm Could you show where this surfaces as an error (e.g. via a screenshot)? I would expect the server, when no definition is found, to just return a `[]` or `null` according to the spec. I wonder if it's the client (`yegapeppan`) doing something weird here.

**Comment by fridayy** [comment]
![module-info-error](https://github.com/erlang-ls/erlang_ls/assets/4015125/4df0c4a7-ece5-41c9-a771-4f262faffe07)

**Comment by carlotm** [comment]
Mine is similar, just a little less fancy :)

![Screenshot_2024-01-08_09-22-42](https://github.com/erlang-ls/erlang_ls/assets/64407038/bbcbbd95-98bc-4e1d-aafa-2bd0f37c98c1)

**Comment by robertoaloi** [comment]
And how does it compare with the case where, for example, you invoke a function which does not exist?

**Comment by carlotm** [comment]
> And how does it compare with the case where, for example, you invoke a function which does not exist?

![Screenshot_2024-01-08_09-50-12](https://github.com/erlang-ls/erlang_ls/assets/64407038/7efe376e-d248-441a-a729-90b1aaa60021)

If the function does not exist in `Mod`, no errors.
In case of a non existing function, same error.

**Comment by plux** [comment]
Yep, this is a bug in CrossRef diagnostics.

**Comment by carlotm** [comment]
Thas was quick! Thank you!
