### ISSUE TITLE
Support for multiple projects in DEBUG mode

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#148]
**Describe the bug**
Currently, a fixed `sname` is specified in the `rebar.config` file to ease debugging. This prevents `erlang_ls` to work with multiple projects.

**Comment by jfacorro** [comment]
It's worth pointing out this only happened when the escript was created with the debug profile.

**Comment by robertoaloi** [comment]
@jfacorro Correct, thanks for pointing that out. Added to the title.

**Comment by jfacorro** [comment]
Fixed by #172
