### ISSUE TITLE
Wrong F/A completion in exports

### ISSUE THREAD

**Issue by MarkoMin** [erlang-ls/erlang_ls#1488]
**Describe the bug**
How can I complete functions to `f/A` instead of `f(Args...)` when trying to export them? When I want to export few functions in export, the first function is correctly expanded to `f/A` (if I autocompleted `-export`), but next ones get wrongly completed to `f(Args...)`. If I don't autocomplete, not even first one works correctly.

**To Reproduce**
Define a module with 2 functions: `really_long_name/3` and `really_really_long_name/3`. Then type "-exp" and autocomplete it to `-export([|]).` (| is cursor mark :D). Now type "really_lo" and hit autocomplete, you'll get "really_long_name/3". Then type ", really_rea" and autocomplete it, you'll get `-export([really_long_name/3, really_really_long_name(Arg1, Arg2, Arg3)]).` - which is wrong I believe. Tested on 0.48.0 and 0.50.0 in `nvim` with `coc` as lsp plugin, OTP26. If I remember correctly this thing worked on VS-code, but I'm not 100%.

**Comment by fridayy** [comment]
Hi @MarkoMin!

I've had this issue with earlier versions but with 0.50.0/master I can not reproduce it.

[bug-0-(3).webm](https://github.com/erlang-ls/erlang_ls/assets/4015125/c6a9455d-dea2-4d17-80da-ab300c2139b3)

I am using nvim v0.9.4 [with this set of plugins](https://github.com/fridayy/nvim-config/blob/master/lua/plugins.lua). Completion provider is nvim-cmp. Maybe this is coc related?

cheers!

**Comment by plux** [comment]
This can happen if parsing of the -export expression fails.
I got an idea how to make it more robust.

**Comment by plux** [comment]
I've merged a fix for this now. Hopefully it will resolve the issue :)

**Comment by MarkoMin** [comment]
Works as a charm, great job!

**Comment by MarkoMin** [comment]
Works as a charm, great job!

**Comment by MarkoMin** [comment]
@plux I just noticed the same thing for `-export_type`
