### ISSUE TITLE
No need to store POIs as annotations

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#150]
After the latest refactoring and the introduction of a DB, it seems un-necessary to store the POIs as annotations in the tree. @jfacorro thoughts?

**Comment by jfacorro** [comment]
I guess it doesn't make sense anynmore. We could just get the list through the `points_of_interest/1` and just store that, right?

**Comment by robertoaloi** [comment]
That would be my guess as well.

**Comment by robertoaloi** [comment]
Actually, we already store the list of POIs in the `documents` table, don't we?

**Comment by jfacorro** [comment]
Yes, exactly. What I meant to say is that we don't really need the annotate functions anymore.
