### ISSUE TITLE
A persistent DB

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#151]
Indexing is an expensive operation. We probably want to persist the indexed data on disk across sessions.

**Comment by alanz** [comment]
It might be worth looking into the [Language Server Index Format](https://github.com/microsoft/language-server-protocol/blob/master/indexFormat/specification.md), introduced in [blog post](https://code.visualstudio.com/blogs/2019/02/19/lsif).

It should result in an ecosystem of tools for managing the files.

**Comment by robertoaloi** [comment]
Interesting, I was not aware of the initiative. Thanks for the links!
