### ISSUE TITLE
Cancellation Support

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#18]
The base protocol offers support for request cancellation. To cancel a request, a notification message with the following properties is sent:

Notification:

* method: `$/cancelRequest`
* params: `CancelParams` defined as follows:

```
interface CancelParams {
	/**
	 * The request id to cancel.
	 */
	id: number | string;
}
```

A request that got canceled still needs to return from the server and send a response back. It can not be left open / hanging. This is in line with the JSON RPC protocol that requires that every request sends a response back. In addition it allows for returning partial results on cancel. If the request returns an error response on cancellation it is advised to set the error code to `ErrorCodes.RequestCancelled`.

**Comment by robertoaloi** [comment]
Lack of this method is evident in VS Code, where the following message continuously appears to the user:

`Method not implemented: $/cancelRequest`

**Comment by alanz** [comment]
I think the client sends it to the server.

**Comment by alanz** [comment]
See e.g. https://github.com/tigersoldier/company-lsp/blob/master/company-lsp.el#L499-L507

**Comment by jfacorro** [comment]
@alanz Yes, this issue is about implementing support in the server for this request. :smile_cat:

**Comment by robertoaloi** [comment]
After some debugging, it's clear what is happening in VSCode.

Whenever using the navigation feature, the user tends to `hover` over the function that she is trying to access. That is enough to trigger a `hover` request, cancelled immediately after due to the `definition` request.
