### ISSUE TITLE
Provide "find module in current project", similar to edts-find-global-function

### ISSUE THREAD

**Issue by seriyps** [erlang-ls/erlang_ls#181]
**Is your feature request related to a problem? Please describe.**
In a big codebase you don't always remember the exact location of a certain module (to which app it belongs to), but you may remember module's name. So, I would like to have some kind of fuzzy search through all the erlang modules in a project.

**Describe the solution you'd like**
To replicate behaviour of `edts-find-global-function`? At least 1st part with global module lookup.

**Describe alternatives you've considered**
In EDTS this tool is called `edts-find-global-function`: https://github.com/robertoaloi/edts/blob/049225db6d7b13db80509f62ad050b361c0d1a33/edts-mode.el#L34

You hit `C-c C-d S-f`and start typing your module's name in minibuffer and this mode provides interactive suggestions of the names of erlang modules from your current project while you typing. When you see the module name you were looking for (you can navigate using left/right arrows), you hit "Enter" and now you are still in minibuffer and it lists all the functions in this module + "jump to the beginning of the buffer", providing the same fuzzy search.

Kind of similar experience can be achieved with `M-x projectile-find-file`, but it has quite slow spin-off time and lists all the project files, not just erlang modules.

**Additional context**
Have to setup EDTS again to make a screenshot. Or can ask co-workers, if needed.

**Comment by jfacorro** [comment]
The feature is avaialble when using [`helm-lsp`](https://github.com/emacs-lsp/helm-lsp)'s function `helm-lsp-workspace-symbol`. I'm attaching a screenshot of what this looks like. 

Would this be fullfill the requirements of the feature you are requesting?

<img width="1680" alt="helm-lsp-workspace-symbol" src="https://user-images.githubusercontent.com/1522569/69517030-d183cf00-0f53-11ea-9e49-3819b7227302.png">

**Comment by jfacorro** [comment]
@seriyps I will close this issue based on the comment above. Please re-open if you have any objections.

**Comment by seriyps** [comment]
Sorry, somehow missed the notification. Yep, it works great. Thank you!
