### ISSUE TITLE
Add OTP libraries as workspace folders

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#187]
Whenever navigating to a OTP library module, the LSP clients asks the user what workspace should be used for that project. We can probably improve the situation by adding the OTP paths as workspace folders.

**Comment by jfacorro** [comment]
I've been thinking about this and workspace folders are an optional feature that clients can choose not to implement, so I don't think we can rely on this 😞.

**Comment by robertoaloi** [comment]
Also, they don't seem to fit our use case. Closing.
