### ISSUE TITLE
Test Language Server with multiple clients

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#21]
Currently the LS has only been tested with a single client and it needs to be modified to support multiple clients at the same time.

**Comment by jfacorro** [comment]
I don't think this is the case though, is it?

As we discussed at some point LSP is more of a server-server setup than client-server. Clients seem to create their own server if there isn't one available. And I'm not sure how multiple clients would work in the STDIO setup.

**Comment by robertoaloi** [comment]
This ticket is definitely outdated. Closing.
