### ISSUE TITLE
implement textDocument/documentHighlight

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#232]
We currently have an implementation of [`textDocument/references`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_references).

Use this as a basis for [`textDocument/documentHighlight`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_documentHighlight)

**Comment by alanz** [comment]
I am planning on working on this.

**Comment by robertoaloi** [comment]
It sounds like a plan!
