### ISSUE TITLE
Add profiler step

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#237]
It is possible to use [eflame](https://github.com/proger/eflame) to profile the indexing process (e.g. the `index_file/index_dir` functions from `els_indexer`.

We could introduce a `profiler` profile in the `rebar.config` which includes eflame and a command that produces a flame graph for a given dir/file. Under the hood, the script would do something like:

```
eflame:apply(els_indexer, index_file, [list_to_binary(filelib:wildcard([code:root_dir(), "/lib/edoc*/src/edoc.erl"])), sync]).
```
Ideally (not necessarily, though), we could add a CI step doing the above for some OTP parts.

**Comment by jfacorro** [comment]
@robertoaloi Do we really need this?

**Comment by robertoaloi** [comment]
@jfacorro No, we don't. Actually removing `eflame` for now.
