### ISSUE TITLE
Add elvis as a source of diagnostics.

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#260]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I can't run my tests because the compile aborts for some silly style error.

**Describe the solution you'd like**

Elvis diagnostics reported in real time (or at least on save), so I can fix them as I work.

**Comment by seriyps** [comment]
Isn't it more of a flymake's job? (In case of emacs)

**Comment by alanz** [comment]
The point is to make it independent of the client (emacs, vscode, vim, atom, ....) and to honour the rules already set up for a given project.
