### ISSUE TITLE
Server crashes on provider's gen_server timeouts

### ISSUE THREAD

**Issue by jfacorro** [erlang-ls/erlang_ls#264]
**Describe the bug**
While the indexing is at its peak CPU consumption, the server's provider might take some time to respond to requests, this results in a timeout which the `els_server` doesn't handle.

**To Reproduce**
Open a (big) project (with a lot of source files and deps in it) and while the indexing is consuming a lot of CPU, try to go to the definition of some funciton, "hopefully" it will cause a gen_server timeout.

**Expected behavior**
Return a `null` result or a notification saying the server is currently busy.

**Actual behavior**
The els_server process crashes.

**Context**
 - `erlang_ls` version (tag/sha): `61aa263`
 - Editor used: Emacs
 - LSP client used: lsp-mode

**Comment by michalmuskala** [comment]
I know that using priorities in processes is normally a terrible idea. However, that is based on service usage, maybe desktop software usage should be treated differently? Would it make sense to set requests to higher priority?

**Comment by jfacorro** [comment]
> I know that using priorities in processes is normally a terrible idea. However, that is based on service usage, maybe desktop software usage should be treated differently? Would it make sense to set requests to higher priority?

We could consider doing that, although I have very little experience tweaking those parameters. 

Maybe we could somehow find a way to limit the amount of processing power the indexing uses. I guess if we limit the amount of workers in the pool to a number one less than the available schedulers (`erlang:system_info(schedulers_online)`), we could almost always count on one of them being available. Unless there's only one scheduler, in which case there's not much we could do.

**Comment by michalmuskala** [comment]
That's definitely a much better idea

**Comment by jfacorro** [comment]
I've been debugging this and the problem seems ot be that there is no worker available in the pool for performing synchronous work. Since the indexing does everything asynchronously and it saturates the pools capacity for some time, then trying to use one of the workers synchronously will always fail.

I think we shouldn't go through the pool at all when requesting a synchronous index of a document, since this happens on synchronous requests from the client, which shouldn't rely on whatever is happening with the pool.
