### ISSUE TITLE
Show indexing progress to clients

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#285]
On project initialization, the indexing process can consume a lot of CPU and memory, which many users have been reporting. Displaying a clear indication that the indexing is happening in the background would improve the user experience.

**Comment by alanz** [comment]
The upcoming 3.15 LSP spec has specific progress support, as at https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#progress

It is currently supported both in emacs-lsp and vscode, so safe for use, I think.  We use it in haskell-ide-engine.

**Comment by robertoaloi** [comment]
I saw that. For now I plan to use basic `showMessage`, until 3.15 becomes the latest official version.
