### ISSUE TITLE
Optional Diagnostics

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#290]
It should be possible to optionally disable types of diagnostics (e.g. elvis, compiler, etc.) via the `erlang_ls.config` file.

**Comment by alanz** [comment]
This could also be configured as a client setting, which then comes through as a `workspace/didChangeConfiguration` message.

But keeping it all in one place as now probably makes sense.

**Comment by robertoaloi** [comment]
This was implementd via #656 .
