### ISSUE TITLE
Refine operator_spaces rules

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#292]
By default, Elvis looks for missing whitespaces only for a limited set of operators. Let's be a bit more strict.

**Comment by jfacorro** [comment]
There's an improved versión of this rule in the lastesr máster of elvis_core. I can tag a new minor release before I do further changes to elvis_core amd we can use that version here.

**Comment by robertoaloi** [comment]
Please do. I will hold on this one and eventually rebase it on top of your changes.
