### ISSUE TITLE
Server crashes in case the module qualifier is a variable

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#30]
Whenever a variable is used as a module qualifier, the server crashes.

**Comment by robertoaloi** [comment]
This should have been solved via #30, but a test case is still required.

**Comment by jfacorro** [comment]
This issue no longer makes sense, right? Since `erlang_ls_tree` currently catches all errors and logs a message.

**Comment by robertoaloi** [comment]
Just verified. Yes, this can be closed.
