### ISSUE TITLE
Add Windows platform to CI 

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#305]
Some users have been reporting bugs in Windows, mostly due to path handling and path separators.
It shouldn't be a problem to support Windows in the server, but if we want to do so we need to add Windows as a platform to our CI pipelines to avoid regressions. I don't even know if this is a possibility in Travis or something else.

**Comment by jfacorro** [comment]
[Clojure on the BEAM](https://github.com/clojerl/clojerl/blob/master/.appveyor.yml) uses [AppVeyor](https://ci.appveyor.com/project/jfacorro/clojerl-jqwev) but it seems that even though you can specify `21.1` the actual version of Erlang/OTP supported is [20.2](https://www.appveyor.com/docs/windows-images-software/#erlang). 😢

**Comment by jfacorro** [comment]
I haven't used Circle CI but it seems like a possibility.

**Comment by alanz** [comment]
I think CircleCI only supports Mac and Linux.  I know they are [investigating Azure](https://github.com/jneira/haskell-ide-engine/tree/hie-bios-azure) for haskell-ide-engine windows builds.

**Comment by michalmuskala** [comment]
Elixir recently started using CirrusCI as one platform to do Linux, Windows, and FreeBSD.

Here's the [config for Linux + Windows](https://github.com/elixir-lang/elixir/blob/master/.cirrus.yml) and a PR for [FreeBSD](https://github.com/elixir-lang/elixir/pull/9599).

**Comment by robertoaloi** [comment]
[GitHub actions](https://github.com/features/actions) seem to support Windows, so we may give them a try.
