### ISSUE TITLE
DB initialization takes up to 10s

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#309]
After we introduced Mnesia, DB initialization started to take a long time. While a time increase is expected, 10 seconds seem excessive. Check what's happening.

**Comment by robertoaloi** [comment]
The delay comes from the `wait_for_tables` operation. Tables load in the following order: signatures, documents, references.

**Comment by robertoaloi** [comment]
This is probably due to Mnesia repairing tables after a non-clean shutdown. This is superseded by #337 .

**Comment by jfacorro** [comment]
I tried both #337 and #338 and neither separately or combined made a difference. I  think it would  make more sense to close those other two and add as tasks the things mentioned in #337 and #338.
