### ISSUE TITLE
Listing all modules takes a lot of time

### ISSUE THREAD

**Issue by jfacorro** [erlang-ls/erlang_ls#312]
Getting all document where the `kind` field is `module`, takes a long time:
```
1> {Time, _} = timer:tc(mnesia, dirty_index_read, [els_dt_document, module, 4]), Time / 1000.
3259.71
```
The same is not true for the `header` kind:
```
2> f(), {Time, _} = timer:tc(mnesia, dirty_index_read, [els_dt_document, header, 4]), Time / 1000.
11.2
```

**Comment by robertoaloi** [comment]
I created #310 for the same reason. Keeping this one and marking #310 as a duplicate.

**Comment by robertoaloi** [comment]
This is because there's currently an index on the 'kind' of the document. Since Mnesia secondary indexes are implemented as `bag` tables where the key is the secondary index and the value is the key, this becomes extremely inefficient in the case (like ours) of a few distinct values indexed.

**Comment by jfacorro** [comment]
We could create a separate table instead, like wee had before the move to mnesia to map the relationship from uri to module.

**Comment by jfacorro** [comment]
Completion is also unusable because it uses `els_dt_module:find_by_id/1` which relied on the other secondary index for documents.
