### ISSUE TITLE
Tighten up id field in poi()

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#368]
At the moment `poi()` is defined as

```erlang
-type poi()       :: #{ kind  := poi_kind()
                      , id    := any()
                      , data  := any()
                      , range := poi_range()
                      }.
```

In practice we only ever use `{F,A}` or `{M,F,A}` for the `id` field.

Define a type for `id` capturing those options only.

**Comment by jfacorro** [comment]
> In practice we only ever use {F,A} or {M,F,A} for the id field.

This is no longer the case, but the main point of this issue is very valid. I will address it in the work done for #486.
