### ISSUE TITLE
Invoke Erlang compiler to generate structured diagnostics

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#371]
**Is your feature request related to a problem? Please describe.**

The language server sends diagnostics to the client, and can generate code actions from them.  This requires knowing technical details of the locations and exact elements being warned about.

**Describe the solution you'd like**

Invoke the compiler using the [`compile:file/2`](https://erlang.org/doc/man/compile.html#file-2) function with the `return` option, which generates structured diagnostics, e.g.

```erlang
{error, 
	[{"test.erl", [{3,erl_lint,{undefined_function,{foo,1}}}]}],
	[]}
```

This was suggested by @michalmuskala in https://github.com/erlang-ls/erlang_ls/pull/314#discussion_r363541489

Note: this is not an "officially" supported feature, but should be stable for a given compiler version, and hopefully does not change much between versions.

**Comment by robertoaloi** [comment]
@alanz I believe this is exactly how the compiler diagnostics are generated on save.

**Comment by robertoaloi** [comment]
@alanz @michalmuskala What is exactly missing in the current server for this ticket?

**Comment by alanz** [comment]
And this behaviour is indeed already present.
