### ISSUE TITLE
Debug mode shows only info level logs

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#377]
Instead, it should also show `debug` entries.

**Comment by jfacorro** [comment]
I thought we didn't want this because of the noise that it would bring to the logs.

**Comment by robertoaloi** [comment]
The current `INFO` logs are currently not really useful, since they don't include the request/response messages. In practice, I often end up making this change locally. After all, in the README `debug` mode is advertised as an opt-in mode, so I don't see the problem with verbose messages. Also consider that we removed the TCP-level messages and that the module content is not present in the logs anymore, so the DEBUG logs are quite ok nowadays. If we still think they're too verbose, we should just remove them.
