### ISSUE TITLE
Specify config file location as a CLI parameter

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#395]
**Is your feature request related to a problem? Please describe.**

Where there is a monorepo with a number of partly related projects under it, it would be convenient to be able to specify configuration at the root of the repo, to be used in all the sub projects.

This may not be structured as a standard rebar project.

**Describe the solution you'd like**

Specify a location for the config file, as a CLI parameter.

**Describe alternatives you've considered**

Other possibilities are via an environment variable. Or both.

**Comment by jfacorro** [comment]
#440 implemented an alternative approach to this.
