### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#4]
Possible candidates:

* Erlang keywords (e.g. `case`, `receive`)
* Variables in the current scope
* Local function names
* Built-in functions (e.g. `now()`)
* Module names
* Macros
* Record names
* Record fields
* Atom names
* Module attributes

**Comment by jfacorro** [comment]
Can we close this one?

**Comment by robertoaloi** [comment]
Now that I created individual tickets for all the above code-completion categories, yes.
