### ISSUE TITLE
Include Erlang in Sublime LSP Package

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#401]
https://github.com/sublimelsp/LSP should include Erlang LS.

**Comment by robertoaloi** [comment]
Something like https://github.com/sublimelsp/LSP/commit/2980d371c07d74e75e0e93f4d83c89147779a946

**Comment by jfacorro** [comment]
Added in https://github.com/sublimelsp/LSP/pull/916#event-3149052036
