### ISSUE TITLE
Detect unused include/include_lib

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#404]
**Is your feature request related to a problem? Please describe.**
I would like to detect unused include/include_lib.

**Describe the solution you'd like**
If an include/include_lib directive is unused in a module, it should be marked as a warning.

**Additional context**
This could be implemented by trying to compile the same file multiple times, excluding one include/include_lib at a time. Since this could be expensive, it could be triggered on demand by the user.

**Comment by michalmuskala** [comment]
Compiling multiple times might sometimes not work correctly, for example with something like:

```erl
%% foo.hrl

-export([foo/0]).

foo() -> ok.

%% bar.erl

-module(bar)

-include("foo.hrl").
```

The module would compile successfully without the include, yet it would change the module.
