### ISSUE TITLE
els_compiler_diagnostics:parse does not handle the error case

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#405]
**Describe the bug**

The function [`els_compiler_diagnostics:parse`](https://github.com/erlang-ls/erlang_ls/blob/fe765af40932d593367786bc41c65d5327e9757d/src/els_compiler_diagnostics.erl#L82-L91) does not deal with the `{error,_}` case.

```erlang
-spec parse(uri()) -> [diagnostic()].
parse(Uri) ->
  FileName = binary_to_list(els_uri:path(Uri)),
  {ok, Epp} = epp:open([ {name, FileName}
                       , {includes, els_config:get(include_paths)}
                       ]),
```

**Context**
 - `erlang_ls` version (tag/sha): fe765af40932d593367786bc41c65d5327e9757d 
 - Editor used:
 - LSP client used:

**Comment by robertoaloi** [comment]
@alanz I'm not sure I get the behaviour you are experiencing. Whenever I include a file which does not exist, I correctly get a compiler diagnostic on that line stating that "can't find include...". How are you triggering this behaviour?

**Comment by alanz** [comment]
To be honest, I triggered it with a test set up the wrong way, then looked at that code and figured it needed to deal with it.

So maybe its not actually needed.

**Comment by robertoaloi** [comment]
Ok. closing this issue and the respective PR, then. We can still re-open them if the error shows up again.
