### ISSUE TITLE
Add support for parse transforms

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#416]
In case parse transforms are used in a module, the compiler reports them as undefined.

**Comment by mynameisdaniil** [comment]
Just observer same behaviour in my case while trying to use `erlang_ls` with `proper`.

**Comment by mynameisdaniil** [comment]
@robertoaloi Looks like it did not help. I'm still having problems with proper and it's `proper_unused_imports_remover` transform. Try it for yourself, include in any program
```
-include_lib("proper/include/proper.hrl").
```
and see how erlang_ls reacts to it.
