### ISSUE TITLE
erlang_ls hangs when multiple editors want to use the same project

### ISSUE THREAD

**Issue by dszoboszlay** [erlang-ls/erlang_ls#418]
**Describe the bug**
Each editor instance wants to run its own `erlang_ls` server for every project it opens. The project determines the path to the Mnesia DB and the node name of the `erlang_ls` server. This means that when multiple editor instances want to use the same project, they both attempt to start an `erlang_ls` server with the same DB path and node name.

`els_db:install/2` attempts to start the distribution protocol, but does not pattern match on the return value of `net_kernel:start/1`. Only the first editor instance's `erlang_ls` server will be able to take the desired node name, for other editor instances `net_kernel:start/1` would fail and the node will continue in nondistributed mode, using the `nonode@nohost` name.

Then `els_db:ensure_db/0` will verify the DB schema exists and starts Mnesia. This works, however Mnesia will believe that all tables exist only on a remote node (the one with the desired node name), not on the local node (`nonode@nohost`). Since it cannot connect to that remote node, it cannot load any of the tables either and `els_db:wait_for_tables/1` would block indefinitely.

**To Reproduce**
1. Open an arbitrary `.erl` file in Emacs.
2. Open the same `.erl` file (or a different one in the same application) in a new instance of Emacs.

**Expected behavior**
`erlang_ls` works in both Emacs instances.

**Actual behavior**
In the second Emacs instance `erlang_ls` hangs in _status:starting_.

**Context**
 - `erlang_ls` version (tag/sha): 5e754db
 - Editor used: Emacs
 - LSP client used: lsp-mode-20200115.950

**Comment by robertoaloi** [comment]
Hi @dszoboszlay ! This is a known issue, but thanks for formalizing this in such a detailed manner. We'll get it fixed as soon as possible.

**Comment by robertoaloi** [comment]
Reference: https://github.com/microsoft/language-server-protocol/issues/23

**Comment by robertoaloi** [comment]
@dszoboszlay I can see two possibilities here:

1. Have a completely separate instance of the DB / server. This would require quite a bit of work and I'm not sure about the advantages.
2. Have both clients interacting with the same server. Not really how LSP is supposed to work at the moment (see referenced issue)

So, not sure about how to proceed with this one. Any reason why you cannot use `emacs-client` instead of `emacs`?

I am leaning towards just refusing the second client in a more obvious way, unless you have a better suggestion.

**Comment by dszoboszlay** [comment]
Completely separate DB instances don't seem to be a good option. Suppose I have two editors open against the same project, and thus I will have two DB instances left on disk when I close them. Now I start a new editor, which DB shall it load? What if I start two editors concurrently, how will they agree on who uses which DB? What if I start three editors the next time? It just doesn't worth it.

I know nothing about the internals of the language server protocol or the way `erlang_ls` stores data in its DB, so I don't really have practical suggestions. If I were to start from scratch, I'd go with an architecture like this:

* There is one dedicated DB node per project. It runs as long as there are at least one editors keeping the project open.
* Each editor launches its own client node for the project, and the client node will connect to the DB node (or start it, if it's not yet running). Each of these client nodes represent one session.
* The DB should store information on the project in two layers. The bottom layer shall represent the state of files as on disk, the upper layer the state of files as they are in the editors. The bottom layer would be shared between sessions (since there's only one copy of the data on disk), but the upper layer would be different for each session (and could actually live in memory only, there's no need to persist it). All the clients would work with a view of the DB that is the bottom layer merged with their session specific upper layer.

However, since you're not starting from scratch, it is probably not feasible to re-architect `erlang_ls` like this. As a practical solution, I'd be happy if the second editor would just get a reasonable error message or whatever instead of just `erlang_ls` hanging there indefinitely.

Regarding `emacsclient`: I don't use it because of personal preference. I open multiple Emacs instances to separate different tasks I'm working on at the same time. So I don't want them to actually become one Emacs session, with one huge buffer list whren it's impossible to keep track of which buffer belongs to which task. But there are some overlaps occasionally, like modules in a library shared between two projects or similar. That's when this bug causes me some headache.

**Comment by robertoaloi** [comment]
I agree that having separate DB instances would create more problems than it solves. We have also been discussing the possibility of decoupling the DB from the server node (basically treat it as an actual, external DB, it could be a single DB using different tables for different projects or a completely different DB per project). This is in principle possible but would complicate things, especially now that we introduced the concept of a _runtime_ node as well and we would like to settle that first.

The multi-layered DB also seems a nice idea, but it will have to wait for a later phase. I'd prefer to keep having a _single tenancy_ language server for the time being and eventually come back to this idea once the project matures.

For now, I think I will just implement a clear error message for the second instance as part of this ticket. At least it will be obvious for the user what's happening.

Regarding Emacs and your use case, did you look at `projectile`? It's quite handy for controlling buffers related to the same project.

**Comment by alanz** [comment]
Maybe we should create a separate issue to track the idea in https://github.com/erlang-ls/erlang_ls/issues/418#issuecomment-620775303, I have been thinking on the same lines.

**Comment by robertoaloi** [comment]
With the latest version of Erlang LS (`0.6.0` or superior), this should not be an issue any longer. Could you please verify it works for you @dszoboszlay ?

**Comment by dszoboszlay** [comment]
Yes, it works for me with 0.6.0, thanks for the fix!
