### ISSUE TITLE
Assistance settings erlang_ls on emacs

### ISSUE THREAD

**Issue by alexandre-kivra** [erlang-ls/erlang_ls#427]
When opening an erlang file I get the following error:

```
Warning (initialization): An error occurred while loading ‘/Users/alexandrejbr/.emacs.d/init.el’:

Symbol's value as variable is void: company-backends

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

I guess I may be missing some configuration? Do you have any idea what could be that I am missing?

**Comment by onno-vos-dev** [comment]
Have you installed `company-lsp` package? And perhaps have you installed any other `company` type packages? Because I've seen others have problems with this :) 

Try merging in stuff from: https://github.com/erlang-ls/erlang_ls/issues/402 :) That basis works but obviously you'll want your other stuff I guess.

**Comment by alexandre-kivra** [comment]
I have the following lines on my `init.el`:

```
(package-install 'company-lsp)
(push 'company-lsp company-backends)
```

That installed the following version:

```
company-lsp        20190612.1553 dependency            Company completion backend for lsp-mode.
```

**Comment by onno-vos-dev** [comment]
Just for funzies, can you try:
```elisp
;; ----- company-lsp -----
;; Enables better integration with company (auto-completion)
(package-install 'company-lsp)
(eval-after-load 'company
    '(push 'company-lsp company-backends))
```
instead of those two lines you showed there

**Comment by robertoaloi** [comment]
Hi @alexandre-kivra !
I think you want to `require` the package, not just `install` it. Alternatively, you need to ensure that the `company-backends` variable is defined when you _push_ a value to it (e.g. like @onno-vos-dev suggested).

Also, I just added a sample Emacs config file and troubleshooting instructions for the Emacs setup at:

https://github.com/erlang-ls/erlang_ls/pull/428

Let us know how it goes!

**Comment by alexandre-kivra** [comment]
That was it @robertoaloi. Thanks!
