### ISSUE TITLE
Allow debug logging via a command line flag

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#430]
**Is your feature request related to a problem? Please describe.**
When trying to debug `erlang_ls` one has to recompile a new binary and reconfigure the LSP implementation to use this new binary to get debug log output.

**Describe the solution you'd like**
A `--debug` flag that enables debug logging and debugging features in the normal binary.

**Describe alternatives you've considered**
None.

**Comment by jfacorro** [comment]
It is possible to start `erlang_ls` with logging enabled by using the `--log-dir DIR` [command-line option](https://github.com/erlang-ls/erlang_ls#command-line-arguments). Is this what you had in mind?

(There's currently a `debug_mode` environment variable that is not really doing anything, it's a leftover after some other changes and should be removed.)

**Comment by robertoaloi** [comment]
This ticket is the result of a discussion I had with @eproxus regarding Erlang LS. It does not really make sense not to start Erlang LS without logs. My suggestion is to:

* Merge the default and debug flavours
* Keep the log dir parameter to specify the location of the logs
* Do not use the log-dir as an implicit way to start logging
* Introduce normal verbosity (`-v` to `-vvv`) for info, debug, etc

**Comment by alanz** [comment]
There seems to be a feature on other language servers, when connecting via stdio, to do log output on stderr, which then shows up in a dedicated log area on the client. This is supported both in vscode and emacs to my knowledge, and probably others.

It should be easy to start erlang_ls to do this.

**Comment by robertoaloi** [comment]
@alanz I'm not sure about using `stderr` for logging. I would prefer to keep the logging consistent between the `stdio` and `tcp` implementations and having logs in the case of `tcp` but not in the case of `stdio` could be confusing. We could _additionally_ forward logs to `stderr` in the case of a `stdio` connection, but I'm not sure. What does the protocol say about this?

**Comment by alanz** [comment]
I don't think the protocol says anything specific about it, this is more a usage thing.

And I agree that additionally forwarding for `stdio` makes the most sense.

**Comment by benrs** [comment]
So for the verbosity of the server I was thinking of directly exposing lager's log level options since they seem quite nice, they support thinks like `=error`, which would only output error logs. This can be done similar to `log-dir` and be called `log-level`. Otherwise an alternative is exposing different levels through different flags, that is `-v` can be mapped to `info`, `-vvv` can be mapped to `error`, and default can be `debug`.

**Comment by robertoaloi** [comment]
@benrs Sounds good to me. I would prefer a `--log-level` rather than `-vvv` to keep the mapping to lager levels straightforward. Default could be `INFO`.
