### ISSUE TITLE
Allow specifying alternative global config file path

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#440]
At the moment the config path lookup code is

```erlang
-spec config_paths(path(), map()) -> [path()].
config_paths(RootPath, #{<<"erlang">> := #{<<"config_path">> := ConfigPath}}) ->
  [filename:join([RootPath, ConfigPath]) | default_config_paths(RootPath)];
config_paths(RootPath, _Config) ->
  default_config_paths(RootPath).
```

This means that if `erlang.config_path` is set, it is interpreted as being relative to the `RootPath`.

It would be useful to provide an alternative `erlang.global_config_path`, which specifies an absolute path for the config file, if it lives in a different location on the filesystem.

This would entail an additional option in the middle, as

```erlang
...
config_paths(RootPath, #{<<"erlang">> := #{<<"global_config_path">> := GlobalConfigPath}}) ->
  [ GlobalConfigPath | default_config_paths(RootPath)];
...
```

This is as an alternative to #395 

master as 769f1f4e044731c4213f0287fdbb80204cfaee40

**Comment by michalmuskala** [comment]
Would it make sense to support just one option, but when `config_path` is relative treat is as relative to root of the project, but when it is absolute allow using any path. It seems a bit more natural and simpler to me than having two separate options.
