### ISSUE TITLE
erlang_ls does not work with the latest version of lsp-mode, Emacs

### ISSUE THREAD

**Issue by featalion** [erlang-ls/erlang_ls#447]
**Describe the bug**
After I went through all the steps to build and configure `erlang_ls` my Emacs I received the following message in Emacs' message buffer:

```
LSP :: The following servers support current file but do not have automatic installation configuration: erlang-ls
You may find the installation instructions at https://github.com/emacs-lsp/lsp-mode/#supported-languages.
```

**To Reproduce**
Using clean installation of Emacs (`~/.emacs.d/` is removed), run Emacs with `/path/to/emacs -q -l /path/to/erlang_ls/misc/emacs`

**Expected behavior**
erlang-ls server is started and Emacs connected to it successfully

**Context**
- `erlang_ls` 2de099a
- macos 10.15.3
- Emacs 26.3
- `lsp-mode` 20200219.1050

**Comment by robertoaloi** [comment]
Hi @featalion . I tried exactly the same configuration, but I was not able to reproduce the issue. Looking at `lsp-mode` it seems that the error message is produced if Emacs cannot start the server correctly (e.g. I get it if I `rm -rf _build` inside `erlang_ls`.

* Is `erlang_ls` in your `$PATH`?
* Can Emacs _see_ the escript? `M-x shell-command` `command -v erlang_ls`
* Did you switch to `zsh` when you migrated to Catalina?

**Comment by featalion** [comment]
Hi, I rebuild the project from scratch, updated the execution path, and now it functions. Not sure what was wrong here. FYI: I use `zsh` as my default shell, but since Tiger, not Catalina.
