### ISSUE TITLE
Compiler errors are reported twice in Emacs

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#464]

**Comment by onno-vos-dev** [comment]
@robertoaloi Does this happen with code_reload enabled or also when it's not enabled? Because if it's the former, you can assign this issue to me and I'll take a look 👍 (Even with the latter I may still pick this up)

**Comment by jfacorro** [comment]
I don't see this behaviour in Emacs.

**Comment by robertoaloi** [comment]
I cannot reproduce this behaviour any longer, it could have been due to outdated Emacs dependencies. Closing.
