### ISSUE TITLE
Find references for records

### ISSUE THREAD

**Issue by jfacorro** [erlang-ls/erlang_ls#465]
Find references for records. It should be possible to find references using:
- The record definition (e.g. `-record(record_name, {foo, bar}).`)
- Record usage (e.g. `#record_name{}`)
- Record field usage (e.g. `#record_name.foo`)

**Comment by michalmuskala** [comment]
Should this also find calls to `is_record/2,3` functions? They are somewhat specially treated by the compiler already.
