### ISSUE TITLE
Elvis diagnostics fail for files not belonging to the project

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#478]
When an OTP file is accessed (e.g. `gen_server`), the server starts calculating diagnostics for it. Elvis diagnostics assume the file is under the same project root directory, which is not true. Therefore, we get a `badmatch`:

     <<RootUri:RootUriSize/binary, RelativePath/binary>> = Uri

```
2020-02-26 08:08:23.899 [error] emulator Error in process <0.1405.0> on node 'erlang_ls_9e94b2f57e580c842c18e0a75dc0820c0f28498a@ws-6fd7bf2f-551b-4644-a930-aa07f7a8860c' with exit value:
{{badmatch,<<"file:///usr/local/lib/erlang/lib/stdlib-3.11.2/src/gen_server.erl">>},[{els_utils,project_relative,1,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_utils.erl"},{line,95}]},{els_elvis_diagnostics,diagnostics,1,[{
file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_elvis_diagnostics.erl"},{line,28}]},{els_text_synchronization,generate_diagnostics,1,[{file,"/Users/robert.aloi/git/github/erlang-ls/vscode/erlang_ls/src/els_text_synchronization.e
rl"},{line,40}]}]}
```

**Comment by alanz** [comment]
Should we even be running Elvis on files outside the project?  In the extreme case, on OTP source?

**Comment by onno-vos-dev** [comment]
> Should we even be running Elvis on files outside the project? In the extreme case, on OTP source?

I don't think we should. I doubt that the majority of OTP source is compliant with most Elvis rules anyway.

**Comment by jfacorro** [comment]
@robertoaloi I'm not able to reproduce this behaviour, in Emacs at least. What editor and client are you using?

**Comment by jfacorro** [comment]
I can reproduce it in VS Code.
