### ISSUE TITLE
Add elvis rule for space after leading comma in a list

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#509]
**Is your feature request related to a problem? Please describe.**

For code like

```erlang
add_underscore_to_unused_var(Config) ->
  Uri = ?config(code_navigation_uri, Config),
  Diag = #{<<"message">>  => <<"variable 'A' is unused">>
          ,<<"range">>    => <<"foo">> }
```

Elvis should complain about a missing space between the comma and `<<` in the last line.

See https://github.com/erlang-ls/erlang_ls/pull/314#discussion_r387090792

**Describe the solution you'd like**

An elvis rule added to the project to warn about the missing space.

**Comment by jfacorro** [comment]
The elvis rule regarding a space after a comma should have catched this, but the thing is that elvis is currently not being run for the test modules.

**Comment by alanz** [comment]
So I guess the issue then is to run it against the test code.
