### ISSUE TITLE
els_compiler_diagnostics:load_dependency/1 may take a while

### ISSUE THREAD

**Issue by onno-vos-dev** [erlang-ls/erlang_ls#513]
**Is your feature request related to a problem? Please describe.**
For large files with lots of dependencies, compiling and loading all dependencies may take some time.

**Describe the solution you'd like**
`els_compiler_diagnostics:load_dependency/1` can probably do this work in parallel to speed things up.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by michalmuskala** [comment]
I don't think parallelizing this would gain much since it all has to go through the code server, which is a singleton.

**Comment by onno-vos-dev** [comment]
Wow, not only did it turn out to not gain much, it even made it worse... (Measured over 50x `els_compiler_diagnostics:diagnostics(Uri)`) 

Good catch @michalmuskala I should have measured this before :-1: Back to the drawing board in terms of trying to optimize the diagnostics more :) 

Master:
| Metric         | Result |
| ---	         | ---	  |
| total_time_ms  | 25124  |
| avg_time_ms    | 502    |
| min_time_ms    | 489    |
| max_time_ms    | 549    |

My branch (that I now declined)

| Metric         | Result |
| ---	         | ---	  |
| total_time_ms  | 26989  |
| avg_time_ms    | 540    |
| min_time_ms    | 453    |
| max_time_ms    | 711    |

**Comment by alanz** [comment]
@onno-vos-dev pay attention the the `sync` and `async` params as well, there is already some logic around this in indexing. Which of course is also subject to the singleton.

**Comment by onno-vos-dev** [comment]
@alanz I'm not sure if we're looking at the same thing here? :) I'm trying to see if the `els_compiler_diagnostics` can be optimized, not the indexer (Which I know Roberto is looking at :) )

**Comment by alanz** [comment]
Oops

**Comment by alanz** [comment]
Thinking about this, the main point is to actually use a worker pool, rather than just spawning some unknown number of processes.  Assuming it was possible of course, which it isn't.
