### ISSUE TITLE
Erlang syntax highlighting for hover information

### ISSUE THREAD

**Issue by jfacorro** [erlang-ls/erlang_ls#516]
**Is your feature request related to a problem? Please describe.**
It would be nice to display Erlang code in the hover information formatted with Erlang syntax highlighting.

**Describe the solution you'd like**
When the client supports markdown, it is possible to specify the language for a block of code by doing the following:

    ```erlang
    -spec foo() -> ok.
    ```

When the client doesn't support markdown it could fallback to the less fancy plain text formatting.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by alanz** [comment]
We do this in the haskell-ide-engine, and it works on vscode and emacs, and have had no complaints from other clients, so assume it works.
