### ISSUE TITLE
Symlink checking is too aggressive

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#520]
**Describe the bug**

If I have a project in a deeply nested directory, and create a symlink to the root of the project, then no apps or deps are indexed anywhere in the project.

So if I have a setup like
```bash
ls -als /home/alanzimm/erl
4 lrwxrwxrwx. 1 alanzimm users 40 Oct 21 00:55 /home/alanzimm/erl -> /data/users/alanzimm/project/server/erl
```

**To Reproduce**

If I set `/home/alanzimm/erl` as the project root, and have an `erlang_ls.config` file specifying a directory under this root, then the `is_symlink` test will exclude it from indexing.

**Context**
 - `erlang_ls` version (tag/sha): a5149fc89abaf9c98846dac57993940384697044
 - Editor used: vscode
 - LSP client used: based on erlang_ls/vscode

**Comment by alanz** [comment]
#339 refers

**Comment by dgud** [comment]
Can we change the implementation to replace symlinks with a the original location,
and not use it if already added to the database?

That would handle the problem with rebar3 _build links as well?

I have a link from:   /home/dgud/src to /mnt/path/src  where src have many projects and something emacs, otp, erlang_ls mixes the rootdir of these so files are not found. 

For example I got these types of error: els_elvis_diagnostics:diagnostics:30 {error,not_relative}
and I have seen other problems.
