### ISSUE TITLE
Add OTP 23 pipeline

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#550]
PR #536 adds support for features introduced in OTP 23. Let's add a pipeline for OTP 23, so we can eventually test it.

**Comment by robertoaloi** [comment]
Re-opening, given we disabled the pipeline for now.

**Comment by robertoaloi** [comment]
@jfacorro Do you remember what was the reason for disabling OTP 23?

**Comment by jfacorro** [comment]
From the logs in the failed builds I would guess it was because of the dialyzer errors regarding the usage of the doc chunk from the `.beam` code.

**Comment by robertoaloi** [comment]
Yes, I saw those as well. But I think there was something "flaky" connected to it.
