### ISSUE TITLE
Maintain a CHANGELOG automatically

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#557]
We could use this to maintain a changelog:

https://github.com/github-changelog-generator/github-changelog-generator

**Comment by jfacorro** [comment]
I've used that for other projects and it works pretty well .

**Comment by robertoaloi** [comment]
Let's give it a try then. My main requirement is to be able to manually tweak the changelog to fix typos and unclear descriptions.

**Comment by robertoaloi** [comment]
Using the GitHub built-in functionality to create the CHANGELOG, so closing.
