### ISSUE TITLE
The md5 of the file is taken twice during indexing

### ISSUE THREAD

**Issue by cauchy-schwarz-inequality** [erlang-ls/erlang_ls#576]
When indexing a new or updated file, we take the md5 hash of the file twice -- once to query the db to see if the file was indexed when we call `els_indexer:index` and once again when we call `els_dt_document:new`. 

This can be addressed by adding an extra argument to `els_dt_document:new`, but as @jfacorro mentioned in `#erlang-ls`, if the performance impact isn't material it might not be worth the added complexity.

**Comment by robertoaloi** [comment]
I did some basic measurements:

Before the change:

* OTP indexing time: 12.5s

After the change:

* OTP indexing time: 12.2s

So, probably not worth.
