### ISSUE TITLE
starting epmd fails if there is a space in the path

### ISSUE THREAD

**Issue by willemdj** [erlang-ls/erlang_ls#577]
When starting the system (on a Windows PC, in combination with VIM), I see an error in the logfile:
`2020-03-17 08:11:56.584 [error] <0.163.0>@els_methods:dispatch:70 Unexpected error [type=error] [error={badmatch,"'c:/Program' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"}] [stack=[{els_db,start_epmd,0,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_db.erl"},{line,139}]},{els_db,install,2,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_db.erl"},{line,30}]},{els_methods,initialize,2,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_methods.erl"},{line,131}]},{els_methods,dispatch,4,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_methods.erl"},{line,65}]},{els_server,handle_request,2,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_server.erl"},{line,137}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{els_server,handle_cast,2,[{file,"c:/Users/lenovo/bin/erlang_ls/src/els_server.erl"},{line,114}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]}]]`

The path to epmd on my machine is: `C:\Program Files\erl10.4\erts-10.4\bin`. 

Probably line 139 in els_db.erl should be changed so that it can deal with this.
 
Note: on my machine `os:cmd(os_find_executable(epmd)).` fails, but  `os:cmd("\"" ++ os:find_executable(epmd) ++ "\"").` works.

**Comment by robertoaloi** [comment]
Hi @willemdj, what version of the server are you using? https://github.com/erlang-ls/erlang_ls/pull/566 was created to support paths including spaces. Could you please verify you are running the latest master?

**Comment by willemdj** [comment]
You are right, that solved the problem. Fixed a few hours after the moment I installed it.

Thanks!
