### ISSUE TITLE
Explore DAP protocol

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#588]
The [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/specification) defines the protocol used between an editor or IDE and a debugger or runtime.

Verify how it could be used for integrating a step-by-step debuggers or even a tracer.

References:

https://github.com/massemanet/redbug
http://erlang.org/doc/apps/debugger/debugger_chapter.html
https://erlang.org/doc/man/dbg.html
https://github.com/hachreak/cedb
https://github.com/etnt/edbg
http://erlang.org/doc/man/int.html

**Comment by michalmuskala** [comment]
Here's the implementation from elixir_ls that ties the `debugger` and `int` with DAP. Potentially some things could be re-used https://github.com/elixir-lsp/elixir-ls/tree/master/apps/debugger

**Comment by robertoaloi** [comment]
@michalmuskala Thanks for the pointer. What about setting up a call where we go through the Elixir LS implementation and discuss what could be reused in Erlang LS?

**Comment by michalmuskala** [comment]
I'm not sure I in particular could help much in here - I'm not very familiar with the code. I mostly added this as a pointer having used it before.

**Comment by alanz** [comment]
Perhaps try to make contact with the Elixir people who implemented this?

**Comment by michalmuskala** [comment]
I got some response from @axelson

>I wouldn't say particularly familiar but I am probably the active person most familiar with it. I'm guessing you've already seen the main entry point:
https://github.com/elixir-lsp/elixir-ls/blob/master/apps/debugger/lib/debugger/server.ex
>
>ElixirLS runs :int.ni on each .beam file in the project:
https://github.com/elixir-lsp/elixir-ls/blob/9637725431e04dea3302f5f4d6e1e098e1ca7706/apps/debugger/lib/debugger/server.ex#L525-L532
>The debugger protocol file does the DAP protocol matching:
https://github.com/elixir-lsp/elixir-ls/blob/master/apps/debugger/lib/debugger/protocol.ex
I think there is some code in the debugger server that could potentially be shared but I think it could be abstracted better.

**Comment by robertoaloi** [comment]
Thanks for the pointers @michalmuskala !
