### ISSUE TITLE
navigation in escripts is broken

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#590]
**Describe the bug**

Handling of escripts was introduced in #580.  We now get syntax highlighting and diagnostics, but features related to indexing are missing, such as go to definition.

**To Reproduce**

Open `erlang_ls/priv/code_navigation/src/diagnostics_warnings.escript.erl` in a client.  Place the cursor on `usage` in line 12, and invoke go to definition.  Nothing happens, even though the function is defined in the same file.

Likewise, trying to go to definitions in other modules also fails.

**Context**
 - `erlang_ls` version (tag/sha): a311fa3ee7e3d0b50ef39b6b1c615f7a496ad4cc
   (actuallly via 05e67f3493d43af11c93b1173f4303b3d9e2f7a4 which is rebased off it) 
 - Editor used: emacs 2.6
 - LSP client used: lsp-mode.

**Comment by robertoaloi** [comment]
Hi @alanz this seems to work correctly now, so closing.
