### ISSUE TITLE
Support for rebar3 projects

### ISSUE THREAD

**Issue by bryanhuntesl** [erlang-ls/erlang_ls#6]

**Comment by robertoaloi** [comment]
Can you expand the description a bit? Are you thinking of something that can detect the structure of a rebar3 repo automatically and add paths, includes, etc accordingly?

**Comment by bryanhuntesl** [comment]
Yes, given a directory which contains a rebar.config file: 

1. Run the language-server according to the rebar3 configuration (default profile).
2. Provide completions based upon the names of project and dependency modules.
3. Call to rebar3 to compile project.
4. Parse compilation errors and present as errors in editor.

**Comment by robertoaloi** [comment]
In the long term, I would like to use something like the Build Language Server from the Scala community:

https://www.scala-lang.org/blog/2018/06/15/bsp.html

For the time being, though, I think we can go ahead with a direct integration with `rebar3`, as long as we create an abstraction layer so that multiple building tools can be used.

**Comment by robertoaloi** [comment]
Adding some thoughts:

An idea is to have the `erlang_ls.config` contain a set of primitive configs, such as `deps_dir` and `include_dirs`. On top of that, we can support a higher level config named `project_type`.
Specifying `rebar3` as the project type would use a callback module to deduce those primitives from the `rebar.config`.
We could also implement a piece of logic that, in presence of a `rebar.config` would just assume rebar3 as the default `project_type`, but I have mixed feelings about that. If we do it, I would still like the possibility to override this behaviour by specifying `project_type: none`.

**Comment by alanz** [comment]
FYI, the equivalent problem in the haskell language server eventually ended up with a specific component to supply the configuration needed, which is extensible.

See https://github.com/mpickering/hie-bios
