### ISSUE TITLE
Poll : should the server info lens be on or off by default?

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#601]
We recently [landed](#585) a code lens to display some information about the erlang_ls server a given file is associated with.  This is currently (via #599) set to be off by default, but can be enabled in server config, by

```yaml
code_lenses:
  - server_info
```

It puts a single line at the very top of the file saying that erlang_ls is active for the file, and what project root directory is in use for the file. This is especially useful in a multi-project-root environment.  The line is clickable, and if clicked a `showMessage` is sent with more server info, including which `erlang_ls.config` file has been loaded for this workspace root.

<img width="630" alt="Screenshot 2020-03-20 at 16 50 13" src="https://user-images.githubusercontent.com/409607/77186506-e409b180-6aca-11ea-9254-c37abcbabefe.png">

The screenshot shows it in action in emacs, after being clicked on, with the info in the message line at the bottom.

But, we are concerned that having this info displayed at the top of every file may be distracting or otherwise unwelcome, and have thus disabled it by default.  It can be enabled via a config file.

But config file loading order is not always clear, as it looks first in the settings (once https://github.com/erlang-ls/vscode/pull/28 lands), then in the project root and failing that in a machine-specific config directory.

One scenario where this lens is useful is identifying which config file is being used for a given project setup.

So, we have a question for users, and ask for votes as follows

- ❤️  leave it as it is, disabled by default, can be enabled via the config file
- 👍  make it enabled by default, can be disabled via the config file
- 💯 some other option, explain in a comment

**Comment by robertoaloi** [comment]
Possibly related: https://github.com/microsoft/language-server-protocol/issues/558
The `ServerInfo` are nowadays also returned by the `initialize` function.

**Comment by robertoaloi** [comment]
@alanz This issue does not seem to get attention from our users. Did we ever asked the question in the Slack channel?

**Comment by alanz** [comment]
I don't think I did.

**Comment by jfacorro** [comment]
Should we close this issue?

**Comment by robertoaloi** [comment]
I guess so, we can reopen it if needed.
