### ISSUE TITLE
Add support for nvim built-in LSP client

### ISSUE THREAD

**Issue by AntoineGagne** [erlang-ls/erlang_ls#603]
Recently, nightly nvim finally merged a [LSP client](https://neovim.io/doc/user/lsp.html) into master.
A [repository](https://github.com/neovim/nvim-lsp) has been made where some default configuration of LSP servers can be found.

I tried adding the following configuration:

```lua
local configs = require 'nvim_lsp/configs'
local util = require 'nvim_lsp/util'

local server_name = "erlangls"

configs[server_name] = {
  default_config = util.utf8_config {
    cmd = {"erlang_ls", "--transport", "stdio"};
    filetypes = {"erlang"};
    root_dir = util.root_pattern("rebar.config");
  };
  -- on_attach = function(client, bufnr) end;
  docs = {
    description = [[
https://github.com/erlang-ls/erlang_ls
]];
    default_config = {
      root_dir = [[root_pattern("rebar.config")]];
    };
  };
};

-- vim:et ts=2 sw=2
```

When the server starts, the client gets response on hover requests and it also gets some diagnostics. However, it does not seem to work on some projects and completion requests always returns null results (I have put an example of the received logs when I try to do completion requests).

It would be nice if the built-in client was supported so we could stop depending on a plugin that asks for `node` dependency.

Sorry if this is not the right place for this kind of request.

# Logs

```
2020-03-22 19:16:11.418 [debug] <0.171.0>@els_methods:dispatch:65 Dispatching request [method=<<"textDocument/completion">>] [params=#{<<"position">> => #{<<"character">> => 15,<<"line">> => 310},<<"textDocument">
> => #{<<"uri">> => <<"file:///home/twain/Documents/Programmation/Erlang/erlang_ls/src/els_methods.erl">>}}]
2020-03-22 19:16:11.418 [debug] <0.171.0>@els_protocol:response:51 [Response] [message=#{id => 31,jsonrpc => <<"2.0">>,result => null}]
```

**Comment by robertoaloi** [comment]
Hi @AntoineGagne and thanks for reaching out. For the projects that do not work as expected, do you have a `erlang_ls.config` file as documented in https://github.com/erlang-ls/erlang_ls#customization ?

**Comment by AntoineGagne** [comment]
I do have a configuration. However, the configuration is the one in my `~/.config/erlang_ls` and it contains the following:

```yaml
otp_path: "~/.kerlenv/"
deps_dirs:
  - "lib/*"
include_dirs:
  - "include"
  - "_build/default/lib"
```

I use [`kerl`](https://github.com/kerl/kerl) for managing my Erlang installations. I don't know if it might be the culprit?

**Comment by robertoaloi** [comment]
Hi @AntoineGagne , @liamjjmcnamara just updated the Vim section of the docs, explaining why the native language server is not used (yet), but it's great that you managed to get it working, those would be precious instructions to add to the docs:

https://erlang-ls.github.io/editors/vim/

Moving to your config, what's the content `~/.kerlenv/`? To get OTP correctly indexed, I have to add:

```
otp_path: "/Users/my/otp/path/lib/erlang"
```

So maybe you're missing the `lib/erlang` part?

**Comment by AntoineGagne** [comment]
Thanks for the answer!

So I tried with `/usr/lib/erlang` (my global installation) and with the `kerl` installation and both didn't work unfortunately... I attached a copy of the logs of the server along with the output of the `tree -L 3` command inside my `.kerlenv` directory (in case I did not put the right path). I also included my `erlang_ls.config`. I can see that the diagnostics works and it seems to have scanned the correct directories.

If you could help me figure out why it doesn't work it would be greatly appreciated. I really like what you guys are doing and I strongly believe that it is a step in the right direction (Erlang really needs some better tools) so I'd really like to help by integrating your effort with the LSP client.


* [`server.log`](https://github.com/erlang-ls/erlang_ls/files/4424500/server.log)
* [`kerlenv-hierarchy.txt`](https://github.com/erlang-ls/erlang_ls/files/4424515/kerlenv-hierarchy.txt)

Content of my `erlang_ls.config`:

```yaml
otp_path: "/home/twain/.kerlenv/21.3/lib/erlang"
deps_dirs:
  - "lib/*"
  - _build/default/lib/*
include_dirs:
  - "include"
  - "_build/default/lib"
```

**Comment by mrrubinos** [comment]
It should be just one line lua config with nvim-lspconfig. See

https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#erlangls

I've just got it running in a breeze.

**Comment by AntoineGagne** [comment]
Yep, it is working correctly now. I don't know what changed since then, but the language server is working correctly on my side too. Since I can't reproduce this anymore, I'll close this issue (I had forgotten about it).
