### ISSUE TITLE
xref cannot find record_info

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#641]
**Describe the bug**

If a module uses `record_info`, the XRef diagnostics reports an error that the function `record_info/2` cannot be found.

According to the [docs](http://erlang.org/doc/reference_manual/records.html)

> To each module using records, a pseudo function is added during compilation to obtain information about records:
>
>`    record_info(fields, Record) -> [Field]`
>`     record_info(size, Record) -> Size`
>
> Size is the size of the tuple representation, that is, one more than the number of fields.

**To Reproduce**

Open a module using `record_info`

**Context**
 - `erlang_ls` version (tag/sha): 7ad7adb1a82b255f9cd947af2083b871ab5cac30
 - Editor used:
 - LSP client used:

**Comment by michalmuskala** [comment]
There's also `module_info` and `behaviour_info` - we should verify they are handled correctly as well

**Comment by alanz** [comment]
I think `behaviour_info/1` is a function that must be provided when defining a behaviour, it is not a pseudo function that is always in scope.

**Comment by michalmuskala** [comment]
`behaviour_info/1` is either explicitly defined or, for modern codebases, a function defined by the compiler for you whenever you use the `-callback` attribute

**Comment by alanz** [comment]
Ok, will see if I can adapt the test case to show that.

**Comment by alanz** [comment]
@michalmuskala 

> `behaviour_info/1` is either explicitly defined or, for modern codebases, a function defined by the compiler for you whenever you use the -callback attribute

I am not able to cause this to appear.  Perhaps you can make a separate issue for this, with an example.

**Comment by michalmuskala** [comment]
We talked a bit more. It looks like there's some quirk in the compiler that doesn't allow calling `behaviour_info(callbacks)` directly in the module, but `?MODULE:behaviour_info(callbacks)` works just fine.
