### ISSUE TITLE
xref cannot find lager:xxx

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#644]
**Describe the bug**

The xref diagnostics report on functions that do not have a definition.

`lager` uses a parse_transform to convert calls such as `lager:info("foo")` into
 something appropriate.  But the xref processing does not know about this, and
 so reports an error because it cannot resolve the reference.

**To Reproduce**

Open a file with a lager logging call in it.

**Expected behavior**

No xref warning for the lager call

**Actual behavior**

The lager call generates an xref error saying it s not defined.

**Context**
 - `erlang_ls` version (tag/sha): 6d0d808ba9804c2e85d5793d620717175821f9f4
 - Editor used:
 - LSP client used:

**Comment by robertoaloi** [comment]
@alanz This is a known behaviour, which will be addressed in https://github.com/erlang-ls/erlang_ls/issues/621

Closing this as a duplicate.

**Comment by robertoaloi** [comment]
If we find this confusing for the user, I'm ok to make the `xref` diagnostics disabled by default.

**Comment by alanz** [comment]
> If we find this confusing for the user, I'm ok to make the xref diagnostics disabled by default.

I think it is a good feature, but the false positives are annoying. Perhaps we should allow specifying a list of functions to filter out in the config file?

**Comment by robertoaloi** [comment]
That list would grow indefinitely, especially if your code makes heavy use of parse transforms. I would rather invest into using real `xref` for this. So #621.

**Comment by codeadict** [comment]
This will be nice to have, I have disabled the xref diagnostic due to parse transforms. Is there any work being done on this, any guidance on what is the plan and how somebody can help?

**Comment by robertoaloi** [comment]
Hi @alanz is the intention to provide a temporary patch for the specific functions while waiting for #621?

**Comment by alanz** [comment]
@robertoaloi I think providing a temporary fix can be useful, especially as it is partly done.

And I understand #621 is on hold too, in favour of doing it with the build node concept.  But, it also needs to work if there is no build node, in a fallback scenario.

**Comment by robertoaloi** [comment]
Sure, we can resume this.
