### ISSUE TITLE
transient proper test failures in CI

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#646]
**Describe the bug**
It looks like we are getting transient proper failures for the xref tests, trying to look up for a document before it is indexed. See https://github.com/erlang-ls/erlang_ls/pull/645/checks?check_run_id=551528841

**Context**
 - `erlang_ls` version (tag/sha): https://github.com/alanz/erlang_ls/commit/6ca0bd9326bde1f864a229a81959b58149979927
 - Editor used:
 - LSP client used:

**Comment by robertoaloi** [comment]
Stacktrace (in case logs from the GitHub actions get cleaned up):

```
[warning] Background job aborted. [reason={{badmatch,{ok,[]}},[{els_xref_diagnostics,run,1,[{file,"/__w/erlang_ls/erlang_ls/src/els_xref_diagnostics.erl"},{line,34}]},{els_background_job,handle_info,2,[{file,"/__w/erlang_ls/erlang_ls/src/els_background_job.erl"},{line,137}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}] [pid=<0.1918.0>]
```

**Comment by robertoaloi** [comment]
It turns out it is not an indexing issue (indexing is disabled in the proper tests). The URIs used by the proper tests are not corresponding to _real_ files, so it is expected that those URIs do not have a corresponding entry in the DB. Most of the times this is not an issue because the diagnostics don't have the time to run during the proper tests, but sometimes that crash happens. Notice that this behaviour (which is easy to fix) is not the root cause of the failing build.

The real issue here is that both the client and the server use integers as the `request id`. Sometimes they end up using the same `id`, so a server-initiated request is occasionally (i.e. depending on timing) considered a response to a client-initiated request with the same id). I am going to fix that.

**Comment by alanz** [comment]
Good. There should be a separate incrementing request id for server-initiated vs client-initiated requests.

**Comment by alanz** [comment]
And in an earlier diff I changed the indexing to always use absolute paths for the files when indexing them, perhaps we should do that in the tests too? We specifiy them in the test as relative, but make them absolute at run time and run the test against the absolute ones.

We do that in the haskell-ide-engine tests too.

**Comment by robertoaloi** [comment]
@alanz How do you keep those ids separate in the Haskell LS? The request id can in theory be a "string", but I suspect many clients may rely on it to be an integer (or the string representation of an integer). In principle, they could collide even if we separate them.

**Comment by robertoaloi** [comment]
And indexing is disabled altogether, so I don't think that's related.

**Comment by alanz** [comment]
> How do you keep those ids separate in the Haskell LS?

A request message can originate in the server or in the client. So the server has a counter which it uses when sending messages,  and the same for the client.  And in the tests we run them in separate processes anyway.  But any tracking of ids clearly distinguishes between whether it is a client or server id.

**Comment by robertoaloi** [comment]
We have that same distinction already now. The client and the server are processes and they keep track of their own IDs. The problem is that:

* Server sends request 1
* Client also send request 1
* Server interprets that as a response, instead

**Comment by alanz** [comment]
This is what we do in `haskell-lsp`

https://github.com/alanz/haskell-lsp/blob/c19ed85e9da8516784415c7144331cabe9e89bf8/src/Language/Haskell/LSP/Core.hs#L620-L628

```haskell
  {-
  Message Types we must handle are the following
  Request      | jsonrpc | id | method | params?
  Response     | jsonrpc | id |        |         | response? | error?
  Notification | jsonrpc |    | method | params?
  -}
```

**Comment by michalmuskala** [comment]
Could a naive fix be to use even numbers as ids for server-initiated flows and odd ids for client-initiated ones? Or is that not under control?

**Comment by robertoaloi** [comment]
The client has a bug in the handling of the messages. I am fixing that.

**Comment by robertoaloi** [comment]
And yes, it is very similar to what the Haskell code does.
