### ISSUE TITLE
Document `code_lenses` and `diagnostics` config option

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#650]
**Describe the bug**

The code currently has the following in config

https://github.com/erlang-ls/erlang_ls/blob/6d0d808ba9804c2e85d5793d620717175821f9f4/src/els_config.erl#L94-L96

These are not documented in the README

**Context**
 - `erlang_ls` version (tag/sha): 6d0d808ba9804c2e85d5793d620717175821f9f4 
 - Editor used:
 - LSP client used:

**Comment by alanz** [comment]
And perhaps we should consider a `negative` config.  Run with normal, but disable a specific one. e.g. disable xref diagnostics only.

**Comment by alanz** [comment]
Right now you cannot configure the diagnostics, because we internally have a binary list, and the config file gives a list of strings.

We also need to filter the strings against available ones, otherwise we try to start a non-existent server.

**Comment by robertoaloi** [comment]
I second the idea of an optional `exclude_diagnostics/code_lenses`.

**Comment by robertoaloi** [comment]
Re-opening since this is also about code lenses, which is not address in #652
