### ISSUE TITLE
VScode now supports semantic highlighting

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#651]
See https://github.com/emacs-lsp/lsp-mode/issues/1482 where they discuss adding support in emacs lsp-mode.  Which means vscode and lsp-mode will be supporting this shortly.

**Comment by jfacorro** [comment]
@alanz I don't understand how this translates to work on Erlang LS, though. Am I missing something too obvious? 😄

**Comment by alanz** [comment]
I am not sure how we would use it either, but as I understand it we can have additional control over syntax highlighting, if we have more information about the context a syntactic element is being used.

In haskell it means you can distinguish between types and constructors, for example, when they have the same name,

**Comment by robertoaloi** [comment]
Tagged this ticket as "investigation" since it will need to be refined before it can be tackled.

**Comment by filmor** [comment]
One thing that would definitely help would be to highlight the first occurrence of a variable within a function. I don't know how often I accidentally used a `State` or something like this again in a `case` and pulled my hair out because it just wouldn't match :-)

**Comment by alanz** [comment]
@filmor this is already possible in the [Document Highlights request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentHighlight) where you can specify a variable as *Write* for the first one, and *Read* for the rest.

**Comment by robertoaloi** [comment]
@alanz I'm closing this since it's not in an actionable state. I'd suggest opening a "discussion" instead of an issue, if we want to investigate this further.
