### ISSUE TITLE
code lens configuration via erlang_ls.config does not work

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#657]
**Describe the bug**
According to #599 we should be able to enable non-default code lenses in the config file.

This does not work, as the config is expressed as binary strings, and these cannot be specified via the config file.

This needs a similar treatment as that for specifying enabled diagnostics providers, as landed in #652.

**To Reproduce**
Add

```yaml
code_lenses:
  - server_info
```

to the config file

**Expected behavior**

When the server starts up, a lens is displayed on the top line of the file.

**Actual behavior**
Nothing happens

**Context**
 - `erlang_ls` version (tag/sha): 4b2a79be3286b6553c2f36a3b84d9f9b5db1dc49
 - Editor used:
 - LSP client used:

**Comment by robertoaloi** [comment]
@alanz Please hold on for this. The refactoring I'm applying to the diagnostics will also affect this.
