### ISSUE TITLE
Add Config for OTP Repo

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#669]
Navigating the OTP repo is a common thing. I suggest we include or document a sample erlang-ls config for users to use. Since the OTP repo structure is quite specific, we may even have a "otp" project type once we introduce the concept.

**Comment by vladdu** [comment]
Not 100% related and I haven't checked the code yet, so this may be a silly question, but do you handle navigating through dependencies (including the OTP code)? If that is a feature that is wanted, then a config is not enough. My idea was to be able to build the POI database for libraries from the CLI and use it without parsing them (which can be slow), similar to how docs are now built into the beam files.

**Comment by robertoaloi** [comment]
Hi @vladdu , you can use the [Erlang LS configuration file](https://erlang-ls.github.io/configuration/) to specify which libraries you consider part of your project and which ones as dependencies. The distinction is used to specify how much information is indexed (vs requested on demand).

OTP is always considered a dependency in this sense (e.g. it doesn't make sense to check whether OTP calls your app functions). Navigation through OTP code works as normal, but the editor will open a new "project" for OTP itself.

At the beginning of the project we went through a phase where we persisted the POIs on disk (using Mnesia), but that turned out not to save too much time (loading the POIs into RAM was comparable with re-performing the indexing) and opened a new category of issues (multiple versions of OTP, stale POIs, etc).

These experiments have been conducted on code bases of millions of lines of code.

So, this ticket is more about generating a configuration for OTP which has a very special structure (e.g. compared to a standard `rebar3` project), so that developers don't have to do it themselves.

**Comment by robertoaloi** [comment]
The minimal config for the OTP repo is:

```
otp_path: "/path/to/otp"
apps_dirs:
  - "lib/*"
include_dirs:
  - "lib"
  - "lib/*/include"
```

**Comment by robertoaloi** [comment]
Added a section to the docs on common configurations (including one for the erlang/otp repo) in https://github.com/erlang-ls/erlang-ls.github.io/pull/52. We can iterate on that page with more and more details/options.
