### ISSUE TITLE
Report parse crashes clearly to the user/developer

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#67]

**Comment by jfacorro** [comment]
Is there a need to do this? I think the approach we currently have is good. All files are "successfully" parsed, even when there might be a chunk that is not parsable.

Sending notifications to the user of what files and where we failed to parse some form, seems a little too much. Alternatively we could create a file under the root URI where wee dump all parsing errors, but how useful would that be for users though?

Any thoughts on this? @alanz @robertoaloi

**Comment by alanz** [comment]
I think what we have now is fine.  The key point is to provide feedback on any file processed, including if parsing fails.  Which we currently do.

Slightly related, the haskell language servers have an ability to confirm their operation from the command line, where you launch it in a project root, and it runs in a mode where it tries to load all the files in the project scope, and reports on success/failure. This is good for confirming your setup, project configuration files etc are all ok, before trying to use it in a client.

**Comment by jfacorro** [comment]
@alanz What operations on files does the haskell command line perform in that case? Just parsing, or it also does something like indexing?

**Comment by alanz** [comment]
In the haskell projects there is no indexing at the moment. But the compiler is invoked on each file, as far as type checking, I think.  Which does generate an in-memory index.

**Comment by robertoaloi** [comment]
I believe we can close this as obsolete. This is from the times when we were "eating" the stacktrace in case of parsing errors.
