### ISSUE TITLE
Define run time node API

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#723]
We are considering having the run-time node take full responsibility for project configuration.

This will result in one configuration for the erlang_ls server and features enabled, including how to start up the run-time node, and another which the run-time node can define and honour for its own use.

Flesh out this concept in terms of an API between erlang_ls and a run-time node.

**Comment by robertoaloi** [comment]
What we could do is to model this API on the one defined by the Build Server Protocol. We don't need the whole JSON-RPC, but we can use Erlang Distribution directly and assume all providers are available. For example, we could have simple methods such as:

* compile
* test
* run

This would allow us  to easily migrate to BSP later on if the protocol starts to get traction in the Erlang world.

Reference: https://github.com/build-server-protocol/build-server-protocol

**Comment by robertoaloi** [comment]
There is even a `sources` request that we can use to get the list of files to index. I like where this is going.

**Comment by robertoaloi** [comment]
And the `buildTarget` maps 1:1 to a rebar3 _profile_.

**Comment by robertoaloi** [comment]
The only thing I'm concerned about is performance. I like the current responsiveness of diagnostics, something that we risk losing with the delegation to rebar3.

**Comment by alanz** [comment]
From slack private chat

> AZ: and it does not have to be a rebar3 build, if performance is not ok
perhaps put a one-shot plugin to rebar. It has the context, which is the important thing, so we can run a private compile, with that context
...
> RA: I'm creating a new repo erlang_bs
> We can define the protocol and a prototype implementation there, the rebar3 plugin will just implement that. 
> Using rebar3's state. Makes sense.
