### ISSUE TITLE
Auto-complete for `-spec ...`

### ISSUE THREAD

**Issue by seriyps** [erlang-ls/erlang_ls#728]
**Is your feature request related to a problem? Please describe.**
Well, it's kind of ergonomical problem.
Let's say you have some function `foo(A, B, C) -> ok.` and you want to add a typespec to it. Then you have to basically re-type the function head again and add type info to it: `-spec foo(A :: type(), B :: type(), C :: type()) -> type().`.

**Describe the solution you'd like**
I would like erlang_ls to be able to auto-complete `-spec <cursor>` with the nearest next function head from the place where I'm typing `-spec`. I guess it will involve some yasnippet integration?

```erlang
-spec <cursor here>
foo(A, B, C) ->
  ok.
```
this should provide a yasnippet autocompleteon with `foo(A :: <>, B :: <>, C :: <>) -> <>.`. If we are not able to figure out variable names, then just have placeholders for types `foo(<>, <>, <>) -> <>.`.
For multi-clause functions we can optionally generate multi-clause typespec:
```erlang
-spec nope(<>) -> <>;
          nope(<>) -> <>.
nope(true) -> false;
nope(false) -> true.
```
but I'm not sure - maybe limit to functions that have not more than ~2-3 clauses.
Maybe we can even try to use `typer` to generate the spec automatically?

**Describe alternatives you've considered**
I don't know any other solutions for this rather than typing manually.

**Additional context**
nope

**Comment by cfclavijo** [comment]
+1. On Emacs there is a skeleton from erlang mode that exposes tempo-template-erlang-* functions, one is the spec that writes a copy of the function with the parameters and a return, however it does not discover the types.
``` erlang
<cursor here + M-x tempo-template-erlang-spec> -spec nope(true) -> undefined.

nope(true) -> false;
nope(false) -> true.
```

**Comment by robertoaloi** [comment]
A ticket for suggest specs via `typer` already exists. See #415 .

**Comment by seriyps** [comment]
Ah, ok. I think my ticket has a bit more details in regards to UI and behaviour description and less of underlying backend suggestions. I even feel like just simple suggestion with function name with templates based on arity might be enough as the 1st step. Gradualizer/TypEr might be a next step (especially when you are working on a new module where functions are not yet fully defined).

**Comment by robertoaloi** [comment]
Erlang LS now supports `snippets`, but they are unfortunately not powerful enough (see their [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax)) to support what you are suggesting.

Considering that [type spec suggestions via TypEr](https://erlang-ls.github.io/articles/suggest-type-specs/) are now also available in Erlang LS, I would close this feature request.

I also plan to start a conversation with the LSP folks about making code snippets a bit more powerful.

**Comment by robertoaloi** [comment]
See https://github.com/microsoft/language-server-protocol/issues/1174
