### ISSUE TITLE
Strings whose last character is ~ break syntax highlighting for code after the string

### ISSUE THREAD

**Issue by kvelicka** [erlang-ls/erlang_ls#730]
**Describe the bug**

If you have a string whose last character is ~, all syntax highlighting for the code after this string will be incorrect. That is, the rest of the code is "highlighted" as if it was part of the same string. This definitely happens on VSCode but I have not tried it on other editors.

**To Reproduce**

Paste the following snippet into an .erl file:

```erlang
hello() ->
    A = "foo~",
    B = bar,
    [A,B].
```

**Expected behavior**

Last two lines are formatted as if they were part of the string.

**Actual behavior**

Last two lines should be formatted as normal Erlang code. In other words, deleting the `A =..` line should not affect the highlighting of the code that goes after it.

**Context**
 - `erlang_ls` version (tag/sha): 0.0.11 (from VSCode extnsion)
 - Editor used: VSCode
 - LSP client used: `erlang_ls` plugin for VSCode

**Comment by robertoaloi** [comment]
Hi @kvelicka and thanks for the report. Syntax highlighting in VSCode is performed via an external library: 

https://github.com/textmate/erlang.tmbundle

I checked and it looks like Erlang LS is up-to-date with it. I would then suggest opening an issue there, instead. If it does not get addressed there, we can try and have a look. Feel free to link this issue there.

**Comment by kvelicka** [comment]
Thanks for the rapid response! I'll open an issue there. Gonna keep this open for now I suppose but I'll close it if the problem gets fixed upstream.

**Comment by michalmuskala** [comment]
Unfortunately it looks like that repo is pretty dead. I tried contributing with some other fixes (there are more issues with syntax highlighting), but didn't get anywhere. I think we should consider creating some community-maintained fork, possibly coordinating with EEF.

**Comment by robertoaloi** [comment]
Sounds good to me.

**Comment by robertoaloi** [comment]
> Unfortunately it looks like that repo is pretty dead. I tried contributing with some other fixes (there are more issues with syntax highlighting), but didn't get anywhere. I think we should consider creating some community-maintained fork, possibly coordinating with EEF.

I don't plan to work personally on that (too many things on my plate right now), but I don't have a problem forking that repo under the `erlang-ls` organization if someone else from this community would like to help maintaining that.

**Comment by robertoaloi** [comment]
Contacted the authors at https://github.com/textmate/erlang.tmbundle/issues/20

Let's see if we get a response.
