### ISSUE TITLE
Fetching OTP docs fails for some functions

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#754]
* gen_server:call
* io:format

```
Reason:     {function_clause,[{shell_docs,get_bullet,[[l],undefined],[{file,"shell_docs.erl"},{line,779}]},{shell_docs,render_element,5,[{file,"shell_docs.erl"},{line,700}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},{shell_docs,render_element,5,[{file,"shell_docs.erl"},{line,639}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1355}]},{shell_docs,render_docs,3,[{file,"shell_docs.erl"},{line,577}]},{shell_docs,render_headers_and_docs,3,[{file,"shell_docs.erl"},{line,538}]}]}
     Offender:   [{pid,<0.184.0>},{id,els_hover_provider},{mfargs,{els_provider,start_link,[els_hover_provider]}},{restart_type,permanent},{shutdown,brutal_kill},{child_type,worker}]
```

Other similar functions such as `gen_server:cast` work fine.

**Comment by alanz** [comment]
I am getting this problem too, with OTP 23.1.1.  In erlang_ls.erl, I log

```
[info] <0.9.0>@erlang_ls:main:25 io:getopts: [[{binary,true},{encoding,latin1}]]
```

**Comment by alanz** [comment]
And the emergency workaround we are deploying internally is https://github.com/erlang-ls/erlang_ls/commit/1939063c8858fe528465a86c547a15dc4e59451c

**Comment by garazdawi** [comment]
This has to do with trying to detect if the printing shell supports unicode in order to print nice unicode bullet-points :). The call that is made is `io:getopts()` which is expected to return a property list with `{encoding,latin1|unicode}` in it. Which process is the group_leader of the process that you are calling the render function from?

**Comment by robertoaloi** [comment]
Of course! And since for the STDIO transport we use a `noop` group leader, the response to a `getopts` request is hard-coded to an empty list:

https://github.com/erlang-ls/erlang_ls/blob/7dcbad1bd9fe5f6a06e2d1b185bf2c94ea65ae61/src/els_sup.erl#L105

**Comment by garazdawi** [comment]
I will add options to shell_docs:render so that you can control that via options instead of reading it from the group leader. I'll put it into OTP-23.2, so for releases before that you need to work with the group leader and return an encoding.

**Comment by alanz** [comment]
> Of course! And since for the STDIO transport we use a noop group leader, the response to a getopts request is hard-coded to an empty list:

Could we use the original values (from the spawning process) instead?
