### ISSUE TITLE
VS Code: "Undefined parse transform" while hovering over a comment

### ISSUE THREAD

**Issue by szTheory** [erlang-ls/erlang_ls#761]
**Describe the bug**
`undefined parse transform 'exercism_parse_transform' Compiler` popup while hovering over a particular comment in VS Code after creating an `erlang_ls.config` file in the project directory for the [Leap Year problem on the Exercism track for Erlang](https://exercism.io/my/tracks/erlang) with the following contents, running `rebar3 unit` (not sure if this is related), then restarting VS Code.

```
include_dirs:
  - "include"
  - "_build/default/lib"
```
![error popup](https://user-images.githubusercontent.com/28652/83918504-64ee5600-a768-11ea-9c9a-cd5ba8ea3519.png)

**To Reproduce**
See above

**Expected behavior**
No error popup

**Actual behavior**
See above

**Context**
 - `erlang_ls` version (tag/sha): 0.0.14
 - Editor used: VS Code
 - LSP client used:

**Comment by robertoaloi** [comment]
Hi @szTheory , where is that parse transform defined?

**Comment by szTheory** [comment]
Sorry, I don't know what a parse transform is in this context. I'm just starting to dig into Erlang. The file is `leap_tests.erl` in the [Exercism project for Leap Year](https://exercism.io/my/tracks/erlang) I linked to above. My uneducated guess is that it's from the [erl_exercism](https://hex.pm/packages/erl_exercism) dependency, as listed in the `rebar.config` with

```erlang
{deps, [{erl_exercism, "0.1.2"}]}.
```

Here is the full `leap_tests.erl`

```erlang
%% Based on canonical data version 1.4.0
%% https://github.com/exercism/problem-specifications/raw/master/exercises/leap/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(leap_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_year_not_divisible_by_4_common_year_test'() ->
    ?assertNot(leap:leap_year(2015)).

'2_year_divisible_by_4_not_divisible_by_100_leap_year_test'() ->
    ?assert(leap:leap_year(1996)).

'3_year_divisible_by_100_not_divisible_by_400_common_year_test'() ->
    ?assertNot(leap:leap_year(2100)).

'4_year_divisible_by_400_leap_year_test'() ->
    ?assert(leap:leap_year(2000)).

'5_year_divisible_by_200_not_divisible_by_400_common_year_test'() ->
    ?assertNot(leap:leap_year(1800)).
```

And here is the full `rebar.config`

```erl
%% Erlang compiler options
{erl_opts, [debug_info, warnings_as_errors]}.

{deps, [{erl_exercism, "0.1.2"}]}.

{dialyzer, [
  {warnings, [underspecs, no_return]},
  {get_warnings, true},
  {plt_apps, top_level_deps}, % top_level_deps | all_deps
  {plt_extra_apps, []},
  {plt_location, local}, % local | "/my/file/name"
  {plt_prefix, "rebar3"},
  {base_plt_apps, [stdlib, kernel, crypto]},
  {base_plt_location, global}, % global | "/my/file/name"
  {base_plt_prefix, "rebar3"}
]}.

%% eunit:test(Tests)
{eunit_tests, []}.
%% Options for eunit:test(Tests, Opts)
{eunit_opts, [verbose]}.

%% == xref ==

{xref_warnings, true}.

%% xref checks to run
{xref_checks, [undefined_function_calls, undefined_functions,
  locals_not_used, exports_not_used,
  deprecated_function_calls, deprecated_functions]}.
```

**Comment by robertoaloi** [comment]
This is your parse transform: https://github.com/NobbZ/erl_exercism/blob/master/src/exercism_parse_transform.erl
I guess you need the following:

```
deps_dirs:
  - "_build/PROFILE/lib/*"
```

In your `erlang_ls.config`, where `PROFILE` is the profile you are using for building (`default`, `test`, etc). Just do a `ls _build` to see which profile you have.

**Comment by szTheory** [comment]
Thanks! I tried a lot of variations of configuration for the `dep_dirs:` configuration and none of them worked after restarting VS Code each time. But for some reason after restoring the original configuration (below) and restarting it worked this time and I no longer get an error in the `test/leap_tests.erl` file. What's strange is that I had already done that before it and still gave me an error.

```
include_dirs:
  - "include"
  - "_build/default/lib"
```

It's probably a lot of work, and maybe it already does this, but I wonder if the configuration could use defaults until they are overridden, or automatically detect the most common configuration based on what paths are in the project dir. Since it seems like the configuration I have above is pretty much a default anyways.

**Comment by robertoaloi** [comment]
Hi!

For a standard `rebar3` project, the Erlang LS config normally looks something like:

```
deps_dirs:
  - "_build/default/lib/*"
include_dirs:
  - "_build/default/lib/*/include"
  - "include"
```

This would be a good default for `rebar3` projects, but in the Community not all projects use it. Once we introduce support for the Build Server Protocol (hopefully soon), it will not be needed any longer to specify such a config, since the build tool will take care of it automatically.
