### ISSUE TITLE
how to quickly generate otp templates?

### ISSUE THREAD

**Issue by jimying** [erlang-ls/erlang_ls#781]
I don't know how to quickly generate otp templates, such as gen_server, gen_event..

Does this extension has this feature？ can anyone tell me how to？

**Comment by gilbertwong96** [comment]
The Erlang-mode of emacs has supported this feature. I suppose it is not the feature erlang_ls should have, it depends on your editor.

Gilbert Wong

**Comment by jimying** [comment]
> The Erlang-mode of emacs has supported this feature. I suppose it is not the feature erlang_ls should have, it depends on your editor. 
>

thanks.  I am an newer to erlang (self-study). 
I use vscode editor with vim extension for my daily c/nodejs development.
Now i want to learn erlang.  how wonderful If an extension can  generate otp templates！

**Comment by robertoaloi** [comment]
Hi @jimying !

You can use [rebar3](https://www.rebar3.org/) to generate those templates.
You can even write your own templates or customize the existing ones. See the documentation at: https://www.rebar3.org/docs/using-templates

Also notice that many OTP behaviour today have optional callbacks (so you don't need the whole boilerplate).

We may introduce support for snippets in Erlang LS in the future. Contributions are always welcome.

**Comment by robertoaloi** [comment]
Closing the issue since it was more of a general Erlang question.
