### ISSUE TITLE
vscode extension erlang  conflict with elang-ls ?

### ISSUE THREAD

**Issue by jimying** [erlang-ls/erlang_ls#782]
**Describe the bug**
vscode install two  extensions erlang and elang-ls，
erlang-ls： for autocomplete
erlang： for debug and autoindent
(erlang extension's git repo: https://github.com/pgourlain/vscode_erlang)

if erlang extension enabled， erlang-ls autocomplete will be become so slowly(need wait for serveral seconds);  
when disable erlang extension，autocomplete is quickly.

I test it on win10 (1909) , debian10, macos 10.14.6 , all  have the same problem.

**Comment by jimying** [comment]
hi, all. 
I found that when open two extensions(erlang,erlang-ls), if file type is  unix type  has problem, 
if use unix2dos command  change file type to dos,  problem disappear.

test as follow:
```bash
$ rebar3 new escript hello
$ cd hello
# default erl file format is unix
$ file src/hello.erl
src/hello.erl: ASCII text
#  hello.erl autocomplete is so slowly

# Now convert to dos type
$ unix2dos src/hello.erl
$ file src/hello.erl
src/hello.erl: ASCII text, with CRLF line terminators

# hello.erl autocomplete is quickly..
```

Maybe this will be help to solve the problem.

**Comment by robertoaloi** [comment]
Hi, the `vscode_erlang` extension also includes a Language Server, so they cannot be used in isolation.
When Erlang LS is launched for the first time, it will index your project in the background. The indexing is necessary before features such as auto-completion and code navigation are available.
I suspect the file type to be unrelated.

Closing since this is expected.

**Comment by jimying** [comment]
ok,  I need a friendly erlang develop env,  the two extensions can Meet
demand（debug, autocomplete, go to define). anyway now it works for me now.

Roberto Aloi <notifications@github.com> 于2020年8月13日周四 上午6:03写道：
