### ISSUE TITLE
misc/dotemacs : company-lsp is not supported anymore

### ISSUE THREAD

**Issue by karlsson** [erlang-ls/erlang_ls#786]
I start emacs (version 26) using the misc/dotemacs file to setup lsp-mode.
Then after opening an erlang file and starting to type in a function name for code completion to trigger I do not get any popup list of possible choices.
In the emacs Messages buffer I can see:
```
LSP :: Connected to [erlang-ls:4181 status:starting]. [2 times]
LSP :: `company-lsp` is not supported anymore. Using `company-capf` as the `lsp-completion-provider`.
LSP :: erlang-ls:4181 initialized successfully
```
If I comment out the the lines;
```
;; Enable code completion
(package-require 'company-lsp)
(push 'company-lsp company-backends)
```
from the dotemacs file, then it works.
Maybe one shall do a package-require on company package itself instead since the company-capf.el is in that package.
I guess that also the lines:
```
;; Override the default erlang-compile-tag to use completion-at-point
(eval-after-load 'erlang
  '(define-key erlang-mode-map (kbd "C-M-i") #'company-lsp))
```
need to be updated.

**Comment by robertoaloi** [comment]
Thanks for the report, the misleading lines have now been removed from the default configuration.
