### ISSUE TITLE
Auto completion of non-local function references

### ISSUE THREAD

**Issue by filmor** [erlang-ls/erlang_ls#790]
**Describe the bug**
When trying to add a non-local function reference (`fun mod:func/2`), the completion adds parameters:

    fun mod:func(Param1, Param2)

> ⚠️ The issue does not occur with local function references, `fun local_func` is correctly completed to `fun local_func/0`.

**To Reproduce**
1. Type

       fun erl_eval:add_bindi

2. Select the completion `erl_eval:add_bindings/3`

**Expected behavior**
Completed as 

    fun erl_eval:add_binding/3

**Actual behavior**
Completed as 

    fun erl_eval:add_binding(Name, Val, Bs)

**Context**
 - `erlang_ls` version (tag/sha): 0.0.14
 - Editor used: VSCode
 - LSP client used: VSCode

**Comment by robertoaloi** [comment]
Thanks for the report, we will look into this asap.
