### ISSUE TITLE
Command "erlang_ls --transport stdio" is not present on the path.

### ISSUE THREAD

**Issue by rubin55** [erlang-ls/erlang_ls#793]
**Describe the bug**
After configuring erlang_ls through lsp-mode:

```
;; Configure lsp erlang mode.
(use-package lsp-mode
  :hook ((erlang-mode . lsp)
         (erlang-edoc-mode . lsp))
 :config
 (setq lsp-erlang-server-connection-type "stdio")
 (setq lsp-erlang-server-path "~/.emacs.d/.local/etc/lsp/erlang_ls/_build/default/bin/erlang_ls"))
```

It seems the setting variables are ignored. Next to that the error message seems to suggest that it is looking for `erlang_ls --transport stdio` as one command:

```
Command "erlang_ls --transport stdio" is not present on the path.
```

**To Reproduce**
Configure emacs with lsp-mode, compile erlang_ls, configure like illustrated above, observe error.

**Expected behavior**
Working lsp-mode for *.erl files.

**Actual behavior**
```
Command "erlang_ls --transport stdio" is not present on the path.
```

**Context**
 - `erlang_ls` version (tag/sha): commit cf430ce742c7a6fee3376afef2b25995b2a79512 (HEAD -> master, origin/master, origin/HEAD)

 - Editor used: Emacs
 - LSP client used: lsp-mode

**Comment by robertoaloi** [comment]
Hi @rubin55 

We provide a default Emacs configuration in `misc/dotemacs`. That's the one we tend to support. May I ask you to start with that configuration?

```
emacs -q -l [PATH-TO-ERLANG-LS]/misc/dotemacs
```

Also, `stdio` is the default transport, no need to specify it. And, if I remember correctly, the transport is a symbol, not a string.

**Comment by robertoaloi** [comment]
Closing for lack of response. @rubin55 feel free to reopen if this is still an issue for you. We are also available on the Erlanger Slack (#erlang-ls channel) for support.
