### ISSUE TITLE
Parse transforms depending on other modules fail

### ISSUE THREAD

**Issue by tomas-abrahamsson** [erlang-ls/erlang_ls#799]
I have a module that needs a parse tranform, and the parse tranform uses another (non-OTP) module, like this:

```erlang
-module(x).
-compile({parse_transform, immediate_dep}).
```

The parse tranform looks like this:
```erlang
-module(immediate_dep).
-export([parse_transform/2]).
parse_transform(Forms, _Opts) ->
    indirect_dep:dummy(), % <--
    Forms.
```

Here's the indirect dependency of the parse tranform:
```erlang
-module(indirect_dep).
-export([dummy/0]).
dummy() ->
    ok.
```

In emacs (for instance) the erlang_ls fails to compile the x.erl and this is the error:
```
    1   0 :error   error in parse transform 'immediate_dep': {undef,
                                           [{indirect_dep,dummy,[],[]},
                                            {immediate_dep,parse_transform,2,
                                             [{file,
                                               "/repo/mob/erlang_ls/src/immediate_dep.erl"},
                                              {line,5}]},
                                            {compile,
                                             '-foldl_transform/3-anonymous-2-',
                                             3,
                                             [{file,"compile.erl"},
                                              {line,1156}]},
                                            {compile,foldl_transform,3,
                                             [{file,"compile.erl"},
                                              {line,1159}]},
                                            {compile,
                                             '-internal_comp/5-anonymous-1-',
                                             3,
                                             [{file,"compile.erl"},
                                              {line,399}]},
                                            {compile,fold_comp,4,
                                             [{file,"compile.erl"},
                                              {line,426}]},
                                            {compile,internal_comp,5,
                                             [{file,"compile.erl"},
                                              {line,410}]},
                                            {compile,
                                             '-do_compile/2-anonymous-0-',2,
                                             [{file,"compile.erl"},
                                              {line,207}]}]}
```
If I comment out the indicated line in `immediate_dep.erl`, no error is indicated for the `x.erl` module.

**Comment by alanz** [comment]
Does #780 make any difference for you?

**Comment by tomas-abrahamsson** [comment]
I'll check

**Comment by tomas-abrahamsson** [comment]
No, unfortunately #780 does not seem to help.

If I attach to the erlang_ls erlang node the below is what I get, both on master and with #780.
```
(erlang_ls_161f8c21ab4d8332c613a40fd01d9268f8611c96@somehost)1> code:which(immediate_dep).
"immediate_dep"
(erlang_ls_161f8c21ab4d8332c613a40fd01d9268f8611c96@somehost)2> code:which(indirect_dep). 
non_existing
```

**Comment by robertoaloi** [comment]
Hi @tomas-abrahamsson and thanks for reporting. I will try to setup a minimal test example with the above information and see if I can manage to reproduce it.

**Comment by robertoaloi** [comment]
@tomas-abrahamsson Can you share your `erlang_ls.config`?

**Comment by tomas-abrahamsson** [comment]
The erlang_ls.config looks like this:
```
apps_dirs:
 - "lib/*"
include_dirs:
 - "lib/*/include"
 - "lib"
deps_dirs:
 - "lib/*"
diagnostics:
    disabled:
     - dialyzer
     - elvis
     - xref
```
I'll try to just indicate relevant parts of the directory structure where it originally happened:
```
   lib/x/src/x.erl
   lib/r/src/immediate_dep.erl
   lib/r/src/indirect_dep.erl
```
Later on, we recreated the same symptoms with the all three .erl files in the erlang_ls/src as can be seen in the stacktrace earlier.

**Comment by tomas-abrahamsson** [comment]
Could it be that we need to set up some paths differently in the erlang_ls.config?

**Comment by robertoaloi** [comment]
I believe that the underlying issue is the fact that, because of how parse transforms work, the `parse_transform` function is _executed_ at compile time. The current algorithm that calculates the module dependencies does not take into account.

I will try to improve the algorithm to use an actual directed graph and to take this into account.

This approach should be revisited. Ideally, once Erlang LS and rebar3 implement the Build Server Protocol, we can simply delegate tasks such as dependency finding to the build tool.

**Comment by robertoaloi** [comment]
@tomas-abrahamsson Could you please check if the current PR solves your issue?

**Comment by tomas-abrahamsson** [comment]
I'm confirming: the PR indeed solves the issue. Thanks!

**Comment by maxno-kivra** [comment]
I stumbled upon this just now, but with a call to a third party dependency instead of internal.

I have one file using a parse transform in a sibling file, that in turn calls a third party module:

```erlang
-module(first).
-compile({parse_transform, second}).
```

```erlang
-module(second).
-export([parse_transform/2]).

parse_transform(Forms, Options) ->
    third_party:func(),
    Forms.
```

```yaml
deps_dirs:
  - "_build/default/lib"
include_dirs:
  - "include"
  - "_build/default/lib"
```

**Comment by robertoaloi** [comment]
@maxno-kivra You should be able to use the brand new `code_path_extra_dirs` option added by @zsoci in #851 which, for scenarios like this, will add the selected dirs (expanding eventual wildcards) to the path.

**Comment by maxno-kivra** [comment]
Wow, that's amazing. And what timing too :heart
