### ISSUE TITLE
I would like M-. to go to variable definition - I think this is a feature request, not a bug

### ISSUE THREAD

**Issue by banjomet** [erlang-ls/erlang_ls#822]
TLDR: M-. works for functions, but not for variables? At least for me.

**Is your feature request related to a problem? Please describe.**
When on a variable, hitting M-. should go and find the first definition of the variable within the function.

**Describe the solution you'd like**
It should look up the variable in the function.

**Describe alternatives you've considered**
Using another erlang/emacs library that can handle that case, but I am trying to keep it simple.

**Additional context**
``` erlang
%% @doc Defines a life cycle of a single agent
-spec loop(agent(), arenas(), sim_params(), config()) -> ok.
loop(Agent "M-. on 'Agent' below should make cursor jump up to here", Arenas, SP, Cf) ->
    case mas_misc_util:behaviour_proxy(Agent, SP, Cf) of
        migration ->
            loop(Agent "M-. here on 'Agent' should move cursor to Agent variable definition" , mas_conc_port:emigrate(dict:fetch(migration, Arenas), Agent), SP, Cf);
        Activity ->
            ArenaPid = dict:fetch(Activity, Arenas),
            case mas_conc_arena:call(ArenaPid, Agent) of
                close ->
                    ok;
                the_end ->
                    mas_concurrent:send_result(Agent);
                NewAgent ->
                    loop(NewAgent, Arenas, SP, Cf)
            end
    end.


```

**Comment by banjomet** [comment]
Just to add, I just installed vscode to see if erlang-ls supports in in vscode, and it does. So this seems to be emacs specific. I am sorry for not detailing that, I made the assumption that people would know I am talking about emacs.

**Comment by robertoaloi** [comment]
Hi @banjomet , _go to definition_ is currently not implemented, so thanks for this feature request. I wonder how it works in VS Code given it's not implemented... 🤔

**Comment by banjomet** [comment]
@robertoaloi hello! I was wondering if I could work on implementing it then. Would that be okay?

**Comment by robertoaloi** [comment]
@banjomet Absolutely! If you want to give it a try, you're more than welcome! Feel free to reach out if you need help!

**Comment by alanz** [comment]
I had a discussion with @richcarl about this recently, and understand it can be done by using the output from [erl_syntax:annotate_bindings/1](http://erlang.org/doc/man/erl_syntax_lib.html#annotate_bindings-1).
