### ISSUE TITLE
Can specify the directory of erlang/otp(not add to system path) for language server?

### ISSUE THREAD

**Issue by iclodq** [erlang-ls/erlang_ls#838]
In my work, project uesed erlang/otp.v.19, and in the version, erlang_ls can't start successfully. Yes, I know, the erlang_ls requirs erlang/otp.v.21 or higher. 
So, I installed otp 23, but can't add it to system path and erlang_ls start failed.  I hope you can support this feature or it has had this feature which I don't know.
I know `erlang_ls.config` has a option `otp_path`, when I set `C:/ptools/erl-23.2/bin` or `C:/ptools/erl-23.2`, the erlang_ls server still start error. I put the `erlang_ls.config` to my project root directory.  Maybe I make a mismake?

And, when I replace otp 23 to otp 19 in system path, it works well!  Buyt I can't do this.

env:
client: vscode 1.52.1  
OS: win10 20H2 
Erlang_LS: Version: 0.0.15

**Comment by robertoaloi** [comment]
Hi!
The version of Erlang LS bundled with the VSCode extension has been compiled with OTP 21, so it will not work with OTP 19.
The alternative for you would be to manually compile Erlang LS using OTP 19 (you may need to patch a couple of things) and to point the VSCode extension (via the settings menu) to point to your version of Erlang LS.
I would also suggest at looking at something like [asdf](https://github.com/asdf-vm/asdf) to handle different versions of the toolchain (erlang, rebar and friends) on the same machine.

**Comment by iclodq** [comment]
@robertoaloi OK， thanks for your suggestion, I will try it.

**Comment by robertoaloi** [comment]
Let us know how it goes. I will close this one since not really actionable from our side.

**Comment by iclodq** [comment]
@robertoaloi  Haha, I was lazy to use a simple way, using win10 WSL. One otp version runs in windows OS, another runs in WSL by vscode remote mode. It's well done. ^_^
