### ISSUE TITLE
Upgrade ranch to 2.x

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#871]
[Ranch](https://hex.pm/packages/ranch/2.0.0) is a dependency used by the TCP transport in Erlang LS (see the `els_tcp` module). The new version of ranch, `2.0.0` has a slightly backward incompatible API and we should migrate to it.

A migration guide is available at: https://ninenines.eu/docs/en/ranch/2.0/guide/migrating_from_1.7/

**Comment by TheGeorge** [comment]
Does anyone use the TCP transport?

**Comment by robertoaloi** [comment]
I've raised this in the past. Limiting Erlang LS to a single transport would simplify the code base significantly (i.e. allowing us to remove the leaky abstraction around the server and the groups in the CT suites). Even if we are going to keep support for TCP, we should look at dropping the dependency on ranch completely. The dependency is big and what we use from ranch should be trivial to implement.

But these are all orthogonal aspects to this PR...

**Comment by robertoaloi** [comment]
According to a poll at Code BEAM Europe 2021, a few people actively use the TCP transport.

<img width="973" alt="Screenshot 2021-05-26 at 08 37 22" src="https://user-images.githubusercontent.com/91769/119613709-b0789480-bdfd-11eb-9cea-c6b3782e8210.png">
