### ISSUE TITLE
The parse transform `proper_unused_imports_remover` is reported as undefined when working on ‘proper’ tests

### ISSUE THREAD

**Issue by ehamberg** [erlang-ls/erlang_ls#879]
**Describe the bug**

When working on a test file that includes `proper/include/proper.hrl`, an error about the parse transform `proper_unused_imports_remover` is always reported.

**To Reproduce**

Clone https://github.com/ehamberg/proper_test and open `test/proper_test.erl`.

**Expected behavior**

No errors should be reported.

**Actual behavior**

An error is reported saying that the parse transform `proper_unused_imports_remover` isn't defined:

     proper_test.erl     1   1 error           undefined parse transform 'proper_unused_imports_remover' (lsp)

**Context**
 - `erlang_ls` version (tag/sha): edef44047255a3647be8291ae2b74e565855b740
 - Editor used: Doom Emacs
 - LSP client used: Whatever is used by Doom

**Comment by robertoaloi** [comment]
Hi, the provided example will work with the following `erlang_ls.config`:

```
deps_dirs:
  - "_build/default/lib/*"
include_dirs:
  - "_build/default/lib/*/include"
  - "include"
  ```
  
Configuration for `rebar3` projects is unintuitive at the moment, but this should go away soon(tm).
