### ISSUE TITLE
[CI] coverage information does not make sense

### ISSUE THREAD

**Issue by TheGeorge** [erlang-ls/erlang_ls#916]
**Describe the bug**
The coverage reported to coveralls does not make sense. Not-executable lines are covered and coverage stops in sequential function in the middle.

**To Reproduce**
Check coverage of e.g. `els_dap_general_provider.erl`

**Comment by robertoaloi** [comment]
I think this is a duplicate of https://github.com/erlang-ls/erlang_ls/issues/693
I think we should move to codecov

**Comment by TheGeorge** [comment]
It is

**Comment by TheGeorge** [comment]
Duplicate of #693
