### ISSUE TITLE
Memory leak? Or to much memory.

### ISSUE THREAD

**Issue by dgud** [erlang-ls/erlang_ls#919]
**Describe the bug**

Update to master today 2021-02-19, and now beam.smp takes **26GB** of memory according to
windows performance monitor, it crashes soon thereafter.

**To Reproduce**
emacs ~/src/otp/lib/observer/test/crashdump_viewer_SUITE.erl
(on windows with wsl, don't know if that matter)

erlang_ls.config used:

diagnostics:
  enabled:
    - bound_var_in_pattern

apps_dirs:
        - "lib/*"
        - "erts/preloaded/"

**Expected behavior**

I used the master branch from beginning of January and that worked fine,
used a lot of memory but not this much.. 

**Actual behavior**
Maybe using below 2GB of memory, so it can be used on 32b machine.

**Context**
 - `erlang_ls` version (tag/sha):   df50bd4b9bd3bf4596e
 - Editor used:  emacs-26.3
 - LSP client used: emacs default ?

**Comment by dgud** [comment]
els_background_job:init process takes 10GB of memory when I watch a restart of erlang_ls.
Growing to 20GB of memory...

ets tables seems stable where els_dt_document stays at 96M  and els_dt_references at 21M.

**Comment by dgud** [comment]
Previously the erlang_ls process becomes ~ 1.5GB.

Bisect gives this commit for me this commit @gomoripeti 

commit 1a7f64da0ce364b6d58734dd22d79275153c9e4d (HEAD, refs/bisect/bad)
 Author: Péter Gömöri <gomoripeti@gmail.com>
 Date:   Fri Feb 12 19:00:59 2021 +0100

    Handle macros in type attributes

    Fixes #908

**Comment by gomoripeti** [comment]
Thanks Dan for the report, I'm trying to reproduce...

**Comment by dgud** [comment]
I'm guessing now, but it takes a while for it to happen, so I guess there is some file in otp
probably not the one I supplied on the command line that causes this, it might be a test file
somewhere which causes an eternal loop or something I have no idea.
Happy hunting.

**Comment by gomoripeti** [comment]
> I wonder if we should really index content of the _data directories.

To test erlang_ls it is definitely useful :) probably less in practice.

I did an experiment loading all of OTP ("deep" indexing) and it takes 1.4GB.
```
11> [{N, V div (1024*1024)} || {N, V} <- erlang:memory()].
[{total,1451},
 {processes,42},
 {processes_used,42},
 {system,1408},
 {atom,5},
 {atom_used,5},
 {binary,95},
 {code,10},
 {ets,1272}]
12> ets:info(els_dt_document, size).
4146
13> ets:info(els_dt_document, memory).
134_391_323 words
14> ets:info(els_dt_references, size).
859468
15> ets:info(els_dt_references, memory).
31_049_304 words
```
Most of the memory is taken up by storing all the POIs/Documents in `els_dt_document`. I wonder if it would help with large projects, to initially not store these Documents during indexing (like https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_indexing.erl#L72, but for every document). The price is that when you open a file you have to reread it again, but I dont think that takes too long, and it is highly likely that only a portion of files will be opened. Of course if someone opens all the files in OTP it will still take 1.4 GBs.

what do you think?

**Comment by dgud** [comment]
> I wonder if we should really index content of the _data directories.

Yeah, ignoring them would be great for me personally since all mnesia files also exists as an old version in dialyser test dir,
which at least a year ago was most often found when jumping to definition, have not tested if it got better recently and 
don't remember if the "hacky" workaround I did as PR got in or not.


I also believe a smaller footprint and re-reading is worth trying, 
but all in all I'm very happy with the progress done in the last year _erlang_ls_ have taken major steps forward.
Great work.
