### ISSUE TITLE
No spec in hover docs since 0.10.0

### ISSUE THREAD

**Issue by gomoripeti** [erlang-ls/erlang_ls#922]
**Describe the bug**
No type specs appear in hover docs even if function has specs. Important to note I use OTP 21 which doesn't have shell_docs. I dont know where else the signatures are used where they might be missing

**To Reproduce**
Hover over a function call, which has a spec defined

**Expected behavior**
Hover docs should show type spec (as well as function clauses and documentation)

**Actual behavior**
Only function clauses and documentation shown, but no spec

**Context**
 - `erlang_ls` version (tag/sha): 1fd8c94137b or 0.10.0
 - Editor used: emacs
 - LSP client used: emacs lsp-mode
 - Erlang/OTP: 21.3

**Some details**

`els_docs` uses specs as a fallback when shell_docs are not available (https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_docs.erl#L64) Signarutes are taken from the data field of `spec` POIs, but since https://github.com/erlang-ls/erlang_ls/pull/909 the format of spec syntax Tree changed and `erl_prettypr` crashes on it. Hence the data in all specs is always empty.

I see few ideas to fix this:
- reimplement/copy/paste relevant part of `erl_prettypr`
- somehow reuse the formatting provider (although that one works on files, not text snippets)
- use the range info in specs to retrieve original spec text from source file (instead of reformatting the parsed syntax tree)

The last option sounds the easiest for me, but there can be other considerations.

**Comment by robertoaloi** [comment]
I agree with your analysis. We should probably start with the last one.
