### ISSUE TITLE
It seems like "-compile(export_all)." is making problem to the erlang_ls parser

### ISSUE THREAD

**Issue by pickme467** [erlang-ls/erlang_ls#948]
During an indexing process the server crashes with the following error:
```2021-03-17 09:26:58.210 [error] <0.7483.0>@els_indexing:try_index_file:129 Error indexing file [filename=/utils/src/helpers.erl, uri=file:///utils/src/helpers.erl] error:function_clause:[{els_parser,find_compile_options_pois,[export_all,[{'-',{16,1}},{atom,{16,2},compile},{'(',{16,9}},{atom,{16,10},export_all},{')',{16,20}},{dot,{16,21}}]],[{file,"/github/erlang_ls/src/els_parser.erl"},{line,117}]},{els_parser,parse_form,4,[{file,"/github/erlang_ls/src/els_parser.erl"},{line,55}]},{els_dodger,parse,5,[{file,"/github/erlang_ls/src/els_dodger.erl"},{line,343}]},{els_parser,parse_file,1,[{file,"/github/erlang_ls/src/els_parser.erl"},{line,28}]},{els_dt_document,new,4,[{file,"/github/erlang_ls/src/els_dt_document.erl"},{line,138}]},{els_indexing,index,3,[{file,"/github/erlang_ls/src/els_indexing.erl"},{line,62}]},{els_indexing,try_index_file,2,[{file,"/github/erlang_ls/src/els_indexing.erl"},{line,127}]},{els_indexing,index_file,1,[{file,"/github/erlang_ls/src/els_indexing.erl"},{line,52}]}]```

I have made a fix that is on my branch and I can just make a PR for this, but I'm not sure if my fix would follow the whole parsing idea. The fix is the following:
```
diff --git a/src/els_parser.erl b/src/els_parser.erl
index 6e87f8d..715fbd2 100644
--- a/src/els_parser.erl
+++ b/src/els_parser.erl
@@ -112,9 +112,11 @@ find_attribute_pois(Tree, Tokens) ->
       []
   end.
 
--spec find_compile_options_pois([any()] | tuple(), [erl_scan:token()]) ->
-        [poi()].
-find_compile_options_pois(CompileOpts, Tokens) when is_tuple(CompileOpts) ->
+-spec find_compile_options_pois([any()] | tuple() | atom(),
+                                [erl_scan:token()]) -> [poi()].
+find_compile_options_pois(CompileOpts, Tokens)
+   when is_tuple(CompileOpts);
+        is_atom(CompileOpts) ->
   find_compile_options_pois([CompileOpts], Tokens);
 find_compile_options_pois(CompileOpts, Tokens) when is_list(CompileOpts) ->
   Fun = fun({parse_transform, PT}, Acc) ->
```
So I extended a guard to check for tuples and atoms. I also updated a spec.

**Comment by gomoripeti** [comment]
thanks for the bug report and fix proposal. Closing as this does not happen any more on latest version.
