### ISSUE TITLE
emacs setup variable void error during startup

### ISSUE THREAD

**Issue by peerst** [erlang-ls/erlang_ls#959]
**Describe the bug**
When using the `dotemacs` setup (also when using it with `emacs -q -l <pathto>/dotemacs`) the following error occurs:

```
Debugger entered--Lisp error: (void-variable it)
  byte-code("\301\10!\205\20\0\302\303\304\305\306\307!!\"!\207" [it file-directory-p file-name-as-directory expand-file-name "resources" file-name-directory find-library-name "lsp-ui"] 6)
  (defconst lsp-ui-resources-dir (byte-code "\301\10!\205\20\0\302\303\304\305\306\307!!\"!\207" [it file-directory-p file-name-as-directory expand-file-name "resources" file-name-directory find-library-name "lsp-ui"] 6) ("/Users/peer/.emacs.d/elpa/lsp-ui-20210326.507/lsp-..." . 502))
  require(lsp-ui)
  (if require-name (require require-name) (require pkg))
  package-require(lsp-ui)
  eval-buffer(#<buffer  *load*> nil "/Users/peer/.emacs" nil t)  ; Reading at buffer position 1423
  load-with-code-conversion("/Users/peer/.emacs" "/Users/peer/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x420756d1>) #f(compiled-function () #<bytecode 0x420756e9>) t)
  command-line()
  normal-top-level()
```
**To Reproduce**
`emacs -q -l <pathto>/dotemacs`

**Expected behavior**
Emacs starts with no error

**Actual behavior**
Debug backtrace see above

**Context**
 - `erlang_ls` version (tag/sha):  `tag: 0.13.0`
 - Editor used: `GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, GTK+ Version 2.24.32)
 of 2020-08-30`
 - LSP client used: dotemacs setup

**Comment by peerst** [comment]
The failing code is here, that's all I could find out:

[https://github.com/emacs-lsp/lsp-ui/blob/78e0a41c9b6b0a166c6c86d2541f310883d15b68/lsp-ui.el#L40](url)

**Comment by peerst** [comment]
Also opened a issue in lsp-ui since it’s likely a client error: https://github.com/emacs-lsp/lsp-ui/issues/601

**Comment by peerst** [comment]
This was a problem in a dependency `dash` probably.  Something got locked up in Emacs packe system.  Either dash didn't install or not correctly.  Updating didn't work and it was also not showing up when listing packages.

In the end deleting the contents of my `.emacs.d/elpa` dir and rerunning at a later point in time has fixed this issue

**Comment by robertoaloi** [comment]
Nice that you found the issue. Thanks for the explanation as well, it may turn useful for some other user!
