### ISSUE TITLE
Do not mark includes as unused if they contain module attributes

### ISSUE THREAD

**Issue by dszoboszlay** [erlang-ls/erlang_ls#964]
**Describe the bug**
The `unused_includes` diagnostic reports include files unused even if they contain module attributes, such as `-compile` directives. E.g. `-include_lib("stdlib/include/ms_transform.hrl").` will always be reported as unused, but removing it would disable an important parse transform.

**Context**
 - `erlang_ls` version (tag/sha): 0.13.0
 - Editor used: VS Code

**Comment by dszoboszlay** [comment]
Just to clarify: there are a handful of module attributes that compiler knows about and treats them in a special way (e.g. `-ifdef`, `-define`, `-compile`, `-include` etc.). The diagnostic shall also understand these and know which one are "unused" (e.g. things inside an `-ifdef` section that is going to be removed by the preprocessor; a `-define` that is not used later etc.). It may even go fancy and report redundant things as unused (e.g. repeated `-compile` options).

But the mere presence of most of these special attributes will change the compiled module, hence the include shouldn't be marked as unused. And if there are module attributes that are not understood by the compiler, they must be preserved too because they will turn up in `module_info(attributes)`.

**Comment by kvelicka** [comment]
+1, got somewhat caught out by `erlang_ls` suggesting `ms_transform.hrl` was unused in a module with a few `ets:fun2ms` calls.
