### ISSUE TITLE
Bound in pattern for named funs

### ISSUE THREAD

**Issue by garazdawi** [erlang-ls/erlang_ls#982]
**Describe the bug**

In the code below:

```erlang
foo() ->
  fun F(#{ level := Level }) ->
    Level
  end.
```
Level is marked as "Bound variable in pattern: Level" when it should not be. If I remove the `F` name it works as expected.

Not sure if this is something that comes from syntax_tools or how erlang-ls uses it.

**Context**
 - `erlang_ls` version (tag/sha): 36bf0815e35db5
 - Editor used: emacs
 - Erlang version: 24.0-rc2

**Comment by gomoripeti** [comment]
thanks, Lukas, for the report. I am afraid this comes from erl_syntax_lib as it looks like it handles `fun_expr` specifically but not `named_fun_expr` https://github.com/erlang/otp/blob/master/lib/syntax_tools/src/erl_syntax_lib.erl#L539

**Comment by garazdawi** [comment]
> I am afraid this comes from erl_syntax_lib as it looks like it handles fun_expr specifically but not named_fun_expr https://github.com/erlang/otp/blob/master/lib/syntax_tools/src/erl_syntax_lib.erl#L539

I thought as much but didn't have time to dig into it when I found the bug. I'll file a bug at https://github.com/erlang/otp, but I don't think we will prioritize working on a fix anytime soon as we don't know much about syntax_tools and do not use it for any of our tools.
