### ISSUE TITLE
Searching for occurrences of atoms in codebase

### ISSUE THREAD

**Issue by ruippeixotog** [erlang-ls/erlang_ls#984]
A common task for me is to search for occurrences of one specific atom. In most cases a simple text search serves the purpose, but the task becomes considerably harder if an atom is short and/or very common in comments or function names.

In IntelliJ I used to do this using their "Find Usages" feature (right click on any atom > "Find Usages"). Can something similar be done in Erlang LS?

**Comment by plux** [comment]
Fixed by https://github.com/erlang-ls/erlang_ls/pull/1404
