### ISSUE TITLE
Invalid Git clone URL in Sublime documentation

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#986]
**To Reproduce**
Go to https://erlang-ls.github.io/editors/sublime3/

**Expected behavior**
URL should be `https://github.com/erlang-ls/erlang_ls`.

**Actual behavior**
URL is `https://github.com/erlang-ls` (missing the repository name).

**Comment by robertoaloi** [comment]
Thanks for the report @eproxus and the fix @gomoripeti !
