### ISSUE TITLE
Make it possible to disable certain hints

### ISSUE THREAD

**Issue by eproxus** [erlang-ls/erlang_ls#987]
**Is your feature request related to a problem? Please describe.**
It is often desired to use bound variables in pattern matching. It is annoying to get hints for these.
```
src/module.erl:
  130:10  hint    Bound variable in pattern: From ​BoundVarInPattern
  130:16  hint    Bound variable in pattern: To ​BoundVarInPattern
```

**Describe the solution you'd like**
A configuration option to disable this (even better, make it the default).

**Describe alternatives you've considered**
None.

**Additional context**
Example code:
```erlang
    case {From, To} of
        {From, To} when From > To -> error(invalid_argument);
        Else -> Else
    end.
```

**Comment by gomoripeti** [comment]
The bound variable hint does not suggest that there is anything wrong or you need to change something. How I use it is just as a syntax highlighting, (for example) just as functions are blue, bound vars are underlined with green.

However if you look at the full list of diagnostics results with compiler and other errors and warnings, then indeed these hints can be noisy.

You can disable this diagnostics in erlang_ls.config as

```
diagnostics:
  disabled:
    bound_var_in_pattern
```
I think what is missing in erlang_ls is if you have a repo specific config, the global config is ignored, so globally disabling might not work (I might be wrong here with config handling)

I don't have a strong opinion though, whether the bound_var_in_pattern diagnostics should be enabled by default or not.

**Comment by eproxus** [comment]
Thanks, I was looking for something like that but couldn't find it in the docs.

I think I would only use this hint if I could limit it to highlighting only and hide it from the diagnostics panel. Also, currently it looks too much like an error or a warning to me. Not sure if it is possible to change this for this hint only (I use Sublime Text 4 and the LSP plug-in).

**Comment by robertoaloi** [comment]
Hi. The diagnostic is already marked as a "hint" (https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_bound_var_in_pattern_diagnostics.erl#L148) and it's up to the editor how hints are rendered. For example, in Emacs, they look like this for me:

<img width="207" alt="Screenshot 2021-04-22 at 17 42 20" src="https://user-images.githubusercontent.com/91769/115743705-31251a80-a392-11eb-9f5d-1bb363b513b1.png">

Maybe there's a Sublime setting regulating how they appear?

**Comment by robertoaloi** [comment]
Hi @eproxus I'm [updating](https://github.com/erlang-ls/erlang-ls.github.io/pull/57) the list of diagnostics in the docs.
Since the `bound_var_in_pattern` diagnostics can already be disabled, I'm closing this one.
