### ISSUE TITLE
Use LSP trace logging facilities

### ISSUE THREAD

**Issue by TheGeorge** [erlang-ls/erlang_ls#992]
**Is your feature request related to a problem? Please describe.**
Currently, the LS logs only it's own log file, which makes issue not surface in the client (unless the LS crashes hard).

**Describe the solution you'd like**
The LSP defines trace log messages, see 
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#logTrace

We should install an additional log-handler that emits these events to the client.

**Comment by robertoaloi** [comment]
@TheGeorge Can we mark this one as done?

**Comment by TheGeorge** [comment]
Yes, I forgot to close the issue.
